### ISSUE TITLE
Carousel not working at all on iOS

### ISSUE THREAD

**Issue by aryandelhi** [smashingboxes/OwlCarousel2#1003]
Owl carousel 2 isn't working at all on any iOS device (with any browser) however it is working perfectly on all other devices.

http://6f342de9e23144987dc316c776f86de1.goldcleats.com/

On last slide.
I have hidden carousel on medium and small device for the time being. Thanks for your help!

**Comment by greg5green** [comment]
Owl Carousel 2 does usually work with iOS devices, but there might be something really unique to your set up that is causing issues. Can you create a test case as described in https://github.com/smashingboxes/OwlCarousel2/blob/develop/CONTRIBUTING.md#bug-reports so we can try debug the issue? I started a [test case](http://codepen.io/anon/pen/doxWaX) already with your settings, so you are welcome to fork that.

Thanks.

**Comment by mijaelsaban** [comment]
Same proble here not working ONLY in IOS device (iphone) , (it's working in safari)
