### ISSUE TITLE
Disable on mobile

### ISSUE THREAD

**Issue by pandroid** [smashingboxes/OwlCarousel2#1015]
Hey,

is there a simple solution to disable OwlCarousel on mobile view?

**Comment by leandroruel** [comment]
if you disable...how about the images? they will stack one on top of each other

**Comment by pandroid** [comment]
Thank you for your reply. But how can I disable only in mobile? I don't need the carousel on mobile view. Only for tablet and desktop.

**Comment by greg5green** [comment]
This isn't a feature of the plugin -- you just need to write some JavaScript and CSS to deal with this.
Something like this JS:
```
if (window.innerWidth > 768) {
  $('.owl-carousel').owlCarousel();
}
```
and this CSS:
```
.owl-carousel {
  display: none
};

@media screen and (min-width: 768px) {
  .owl-carousel {
    display: block;
  }
}
```

This is a personal support request, so please take any further questions to [StackOverflow](http://stackoverflow.com/questions/tagged/owl-carousel) as described in https://github.com/smashingboxes/OwlCarousel2/blob/develop/CONTRIBUTING.md

**Comment by nathpaiva** [comment]
Hey I know it was closed but i think it's better .destroy() 

With it you can use images but without carousel! It depends what you wanna do!

**Comment by maxleistner** [comment]
+1 i would rather add an destroy option like slick slider. You can then easily use it within responsive options.
