### ISSUE TITLE
Many carousels on a single page

### ISSUE THREAD

**Issue by eshem** [smashingboxes/OwlCarousel2#1026]
Hi there,

I am developing an application that has a single page with many carousels showing multiple images.

Let's say 500 carousels with 5 images each. As I add the carousels (they are loading with pagination), FPS levels drop massively, and jank increases to the point where the page can barely be used.

Some clues, it seems that autorefresh is constantly be pinged. Once the carousels are placed on the page, they are not touched (nothing added or removed to particular carousels). They are all being initialized with common settings, similar to below. 
```
   $('.blah-item').owlCarousel({
     lazyLoad:true,
     mouseDrag: false,
     loop:true,
     items: 1,
     nav: true,
     navText: navButtons,
     dots: false
    });
  }
```

I tried things like killing autorefresh and reducing autorefresh time, however on the initial load it takes quite long to make the carousels appear. Additionally, I tried changing 
```
this._interval = window.setInterval($.proxy(this.refresh, this), this._core.settings.autoRefreshInterval);
```
to 
```
this._interval = window.setTimeout($.proxy(this.refresh, this), this._core.settings.autoRefreshInterval);
```

Please let me know if you could think of anything that would increase the speed or efficiency, or help in stripping out some features I am not using. Please let me know if I can provide further information.

Thanks in advance!

**Comment by iandonovan** [comment]
Hi!

We have no intention of supporting 500 concurrent carousels.
