### ISSUE TITLE
Remove nav button at ended loop direction

### ISSUE THREAD

**Issue by ihabovich** [smashingboxes/OwlCarousel2#1041]
I imagine that a must wanted featured is to remove the nav button when assigned loop direction ends. Most carousel does!

**Comment by jacobkossman** [comment]
$(".owl-carousel").on('changed.owl.carousel', function(event) {
	    if(event.item.index+6 == event.item.count){
		    $(this).find(".owl-next").hide();
	    }
    });

change 6 to the number of items shown at one time :+1:

**Comment by ihabovich** [comment]
@jacobkossman So, how to make it work for both directions. I see your solution is working for next items but not previous ones!

**Comment by greg5green** [comment]
This is already functional in beta 3. http://codepen.io/anon/pen/epJBvm

**Comment by ihabovich** [comment]
Nice work :+1:

**Comment by Makushime** [comment]
Hi @greg5green, maybe you know it already, but there is a regression on beta 4. The "disabled" classes aren't there anymore.

I had the beta 4 on my project and the classes weren't there, so I changed the version to beta 3 and they appeared.

**Comment by greg5green** [comment]
@Makushime The latest version is 3 -- there is no 4 yet? Or do you mean from the develop branch?

**Comment by Makushime** [comment]
@greg5green, my bad. I mistook the beta 2.4 for a beta 4. That's the version that I used originally on my project. Sorry for the confusion.

**Comment by greg5green** [comment]
@Makushime :+1:
