### ISSUE TITLE
dots navs not working when set dotsContainer

### ISSUE THREAD

**Issue by liquida** [smashingboxes/OwlCarousel2#1043]
hello guys, when i set the dotsContainer, the navigation dots are not working

they only shows 2 dots

 $('.liquida_owl').each(function() {

                var $container = $(this),
                        $jcarousel = $container.find('.owl-carousel');

$jcarousel.owlCarousel({
                    loop: true,
                    nav: false,
                    navText: ['<i class="fa fa-angle-left"></i>', '<i class="fa fa-angle-right"></i>'],
                    //navContainer: $container.find('.controls-buttons'),
                    dots: true,
                    //dotsClass: 'controls-pagination',
                    dotsContainer: $container.find('.controls-pagination'),
                    items: layout_slides,
                    margin: layout_gutter,
                    responsive: layout_resize,
                    autoplay: autoplay,
                    autoplayTimeout: autoplay_speed,
                    autoplayHoverPause: true,
                    smartSpeed: speed,
                });

**Comment by greg5green** [comment]
Please document this issue as described in [CONTRIBUTING.md](https://github.com/smashingboxes/OwlCarousel2/blob/develop/CONTRIBUTING.md#bug-reports). Thanks

**Comment by liquida** [comment]
hello, it was my mistake. Thanks!
