### ISSUE TITLE
Remove/Delete/Reset

### ISSUE THREAD

**Issue by cblaze22** [smashingboxes/OwlCarousel2#1052]
I have tried just about everything with trying to reset the carousel with new items after an ajax request.  I'd like to delete all items in the carousel and load it up with new ones.  However everytime they keep coming back event after a destory, remove from an index, etc.  Any help here?

2.0.0-beta.3

**Comment by digz6666** [comment]
Happening for me too, have you resolved your issue?

**Comment by cblaze22** [comment]
This is the only thing that worked for me.

'''
if (typeof $(element).data('owl.carousel') != 'undefined') {
                            $(element).trigger('destroy.owl.carousel');
                            $(element).html('').removeClass('owl-loaded');
                        }

                        if (ads) {
                            for (var i = 0; i < ads.length; i++) {
                                ad = ads[i];

                                li = $('<div class="owl-original">');

                                image = $('<img>', {
                                    src: ad.Image,
                                    alt: ad.Name,
                                    'class': 'owl-lazy',
                                    'data-src': ad.Image
                                });

                                link = $('<a>', {
                                    target: '_blank',
                                    title: ad.Name,
                                    href: ad.Link
                                });

                                link.append(image);
                                li.append(link);

                                $(element).append(li);
                            }
                            $(element).owlCarousel(values.carousel);
                        }
'''
