### ISSUE TITLE
How to destroy the carousel?

### ISSUE THREAD

**Issue by leolux** [smashingboxes/OwlCarousel2#1064]
The documentation is missing an explanation how to destroy the carousel and I tried two methods without success:

```
Owl.destroy(); // <-- Owl is not defined
$('.owl-carousel').destroy() // <-- destroy is not a function
```

Any suggestions?

**Comment by greg5green** [comment]
http://smashingboxes.github.io/OwlCarousel2/docs/api-events.html#destroy-owl-carousel
