### ISSUE TITLE
Chrome 45: stage moves up on drag

### ISSUE THREAD

**Issue by constantin-iliescu** [smashingboxes/OwlCarousel2#1083]
This happens on latest chrome (Version 45.0.2454.101).
You can see it on the project's demos page:

http://smashingboxes.github.io/OwlCarousel2/demos/basic.html

If you use the dots, the slider behaves correctly.
If you drag it with the mouse, the stage will move 8px up.
This seems related to the overflow: hidden; rule set on the outer stage, but I could not find a solution so far.

**Comment by IgorCode** [comment]
Did you update to Chrome 46 and if you did does it still happen?

I experienced this behavior before, although for me this was definitely more than 8px, now I can't reproduce it (I'm on Chrome 46 now).

**Comment by constantin-iliescu** [comment]
Hi, 
The issue was not from Chrome, but from an extension. It's called Smooth Key Scroll (https://chrome.google.com/webstore/detail/smooth-key-scroll/gphmhpfbknciemgfnfhjapilmcaecljh/support?hl=en).
This extension has issues in both 45 and 46 Chrome versions.
