### ISSUE TITLE
Question: How to have 2 sliders on a page

### ISSUE THREAD

**Issue by lenamtl** [smashingboxes/OwlCarousel2#1099]
I'm looking the way to use the script with ID.
I need to show 2 sliders on the same page with different settings.

Any instruction or snippet?

Thanks

**Comment by usb248** [comment]
Do you know how to read a documentation ?

**Comment by lenamtl** [comment]
Hi, of course I have read the docs...

I didn't see any example with IDs for the slider and for controlers.

I was updating my previous code OwlCarousel1 to OwlCarousel2 
and for any reason it's not working properly.

So if you have any info about it let me know.

For know I will keep OwlCarousel1

**Comment by rafael-renan-pacheco** [comment]
The key here is the jQuery selector.

You can have in your html:

```
<div class="owl-carousel owl-theme" id="first-id">
  <div> Your Content </div>
  <div> Your Content </div>
</div>

<div class="owl-carousel owl-theme" id="second-id">
  <div> Your Content </div>
  <div> Your Content </div>
</div>
```

And in your JS:

```
$(document).ready(function(){
  $('#first-id').owlCarousel(); /* plus your first configuration */
  $('#second-id').owlCarousel(); /* plus your second configuration */
});
```

You don't have to use "$('.owl-carousel')", this is just the docs example.

Best regards.

**Comment by lenamtl** [comment]
Thanks
