### ISSUE TITLE
Don't ignore the /dist folder

### ISSUE THREAD

**Issue by adampatterson** [smashingboxes/OwlCarousel2#1136]
So I am using require.js with Bower and locally everything is fine.

I had a look at my bower settings for Owl and It is using 'latest' Cool, Check my site out on my server and Owl is now missing. I do a bit of digging and see that the `/dist` folder is missing.

Bower/Grunt everything and the folder is still ignored.

Basically by ignoring the `/dist` folder makes this package unusable without moving files around.

https://github.com/smashingboxes/OwlCarousel2/blob/develop/.gitignore#L12

**Comment by bravedick** [comment]
+1

**Comment by greg5green** [comment]
The dist folder is included in beta 3. https://github.com/smashingboxes/OwlCarousel2/tree/2.0.0-beta.3

**Comment by bravedick** [comment]
Why this ticket is closed. I still see /dist in gitignore in last version. It should be removed from gitignore.

**Comment by greg5green** [comment]
The Bower releases are based off the master branch, which does not have dist in it's [gitignore](https://github.com/smashingboxes/OwlCarousel2/blob/master/.gitignore).

This was changed in https://github.com/smashingboxes/OwlCarousel2/commit/1333765e059b76cf366f59531721b2ed318f1ab6. Although beta 3 is one commit behind master at the moment and does not include this commit, it still includes the dist directory when doing a bower install when installing either a specific version, like `~2.0.0-beta.3` or just the `latest`.
