### ISSUE TITLE
Blurred text on slide (Chrome 35)

### ISSUE THREAD

**Issue by pe6o** [smashingboxes/OwlCarousel2#120]
Hi, I was so surprised to see v2 of your awesome plugin. I'm testing it right now and I stumbled upon a bug in Chrome. Sometimes on slide I get a blurred text on Chrome 35.

Check this fiddle http://jsfiddle.net/vNtum/2/ and slide once.

The titles of the slides get blurred. I'm not sure if this is a plugin bug or something with Chrome?

Tried adding:
```
 -webkit-backface-visibility: hidden;
 -webkit-transform: translateZ(0) scale(1.0, 1.0);
```

... to the parent element, but it didn't worked.

Before:
![](http://i.snag.gy/O0k3e.jpg)

After:

![](http://i.snag.gy/VxF8b.jpg)

If you still don't see it, resize the HTML window width.

There is also a 1px "space" bug between this slides. How can this be fixed?

**Comment by jonmilner** [comment]
Confirmed that this is a sub-pixel rounding issue. The only situation in which I see this being a potential issue is when the margin has been set to 0 (leaving no space between the slides). Like @carasmo said, it's barely noticeable when using photos. A background color can be added to ".owl-stage" that matches the background of the slides to hide the issue even further. Or use "margin: 0 -1px" if it's still an issue.
