### ISSUE TITLE
Beta4 to Github ?

### ISSUE THREAD

**Issue by divinoro** [smashingboxes/OwlCarousel2#1208]
Hello, any possibility to push Beta4 to github ? We are using Bower, but beta3 is causing some issues, so we are forced to keep beta4 in our local git.

Thank you.
Ivan

**Comment by tdecaluwe** [comment]
@divinoro I think you're referring to the beta 2.4 release which was released prior to the beta 3 release. What kind of problems are you seeing?

**Comment by divinoro** [comment]
Ah, sry, then it's missunderstanding :)

..anyway: using version from this latest repo is causing some strange behaviour. We are using 2 carousels in one page, 1st is working well, 2nd is creating a big empty space and displaying nothing. Strange thing is, that in 2.4 was working well. Do we have any changelog or something like that ? Maybe we did some worng configuration. Params are as following:

`$('.owl-carousel2').owlCarousel({
                loop: true,
                nav: true,
                autoplay: true,
                autoplayTimeout: 3000,
                autoplayHoverPause: true,
                autoplaySpeed: 2000,
                dots: false,
                navText: ["<i class='fa fa-chevron-left fa-lg'></i>&nbsp;","&nbsp;<i class='fa fa-chevron-right fa-lg'></i>"],
                responsiveClass: true,
                responsive: {
                  0: {
                    items: 1
                  },
                  450: {
                    items: 2
                  },                  
                  700: {
                    items: 3
                  },
                  1000: {
                    items: 4
                  }
                }
              });`

**Comment by tdecaluwe** [comment]
That's not good :) Perhaps open a separate issue describing what you're seeing, including an example demonstrating the problem. If you've got a github repo you can try to find out in which commit you're carousel stopped working. Does the issue arise in the `2.0.0-beta.3` or only on the current `develop` branch?

**Comment by divinoro** [comment]
I've finally identified this commit, which is causing stuff to not working:

https://github.com/smashingboxes/OwlCarousel2/commit/d33a9ee3b53e87dbf98f53def01342fc50189e33

Unfortunately it's bigger one, will try to find what exactly is problem.

Unfortunately I can't share it right now, because it's in private network.

**Comment by divinoro** [comment]
I have opened new #1217 with further details / example.
