### ISSUE TITLE
LazyLoad with stagePadding not loading images.

### ISSUE THREAD

**Issue by louiswalch** [smashingboxes/OwlCarousel2#1210]
When using lazyLoad: true, stagePadding: 70, the images displayed in stage padding are not loaded.

![preview](https://cloud.githubusercontent.com/assets/286013/12800855/162a4b44-caa6-11e5-8509-f39f1eb38398.png)

**Comment by clooth** [comment]
I've had this same problem. I made my own quick fix using a patch like this in the un-minified source inside the Lazy plugin:

Add to default settings for the plugin:

Line 1843: `lazyLoadEager: 1`

Add to the `._handlers` function:

Line 1819: `settings.lazyLoadEager && (n += settings.lazyLoadEager);`

**Comment by louiswalch** [comment]
Thanks for the help.
Do you know if there is any way to detect which slides are the ones being displayed as partial slides inside the stagePadding and to apply a class to them?

**Comment by louiswalch** [comment]
Can you show a screenshot or more complete source for your line 1819 changes? Line numbers are not matching up and not sure what you are updating in `._handlers`

**Comment by clooth** [comment]
I'm talking about this line: https://github.com/smashingboxes/OwlCarousel2/blob/develop/src/js/owl.lazyload.js#L52

Just add the extra line of code there.

**Comment by louiswalch** [comment]
I haven't been able to get it working. Added to that line but elements in stagePadding are still not lazy loaded. Possible to attach your file?

![owl_carousel_js_ _static](https://cloud.githubusercontent.com/assets/286013/13551287/50b99796-e302-11e5-8bd2-3eda26724a54.png)

**Comment by clooth** [comment]
Hey @louiswalch, sorry for the delay.

I replaced the lines you added with the following:

```
settings.lazyLoadEager && (n += settings.lazyLoadEager + 1); // +1 is for accomodating both sides
settings.lazyLoadEager && (position -= settings.lazyLoadEager);
```

Please post a jsfiddle or jsbin of your code so I can take a look if you don't get it working. :)

**Comment by louiswalch** [comment]
Tried this new code.On my local computer it loads the one on the right, but not left. When I created a JSFIDDLE it doesn't load either ones in stagePadding.

Check out line 1828. Had to load all the Owl JS, didn't know how else to do it. My init is at the very bottom of JS.

https://jsfiddle.net/louiswalch/9ed9mbvv/3/

**Comment by clooth** [comment]
@louiswalch but you haven't even added the other line.

```
Lazy.Defaults = {
    lazyLoad: false,
    lazyLoadEager: 1 // <-- You never added this line.
}
```

**Comment by louiswalch** [comment]
Oh my gosh. So sorry about that, I reverted back to original file when I made your last change and that got dropped. Thanks for the help, all working!

**Comment by clooth** [comment]
@louiswalch Also, I went ahead and made you a small personalized tweak to add classes to those surrounding blocks. It might not work in every case but here: https://jsfiddle.net/23mmpmsz/
