### ISSUE TITLE
Dots remain hidden

### ISSUE THREAD

**Issue by dorothyDorothy** [smashingboxes/OwlCarousel2#1218]
I cannot get the dots to appear.

Here is a snippet of my code in question:
https://jsfiddle.net/1bksf5c7/

The height of the dots element remains collapsed even when I set dots to true.  I am using owl.carousel.2.0.0-beta.2.4 
I've included owl.carousel.css and owl.theme.css, is there some css that I'm missing?

**Comment by swim** [comment]
For some reason there are two project pages for Owl Carousel,
- http://www.owlcarousel.owlgraphic.com
- http://smashingboxes.github.io/OwlCarousel2

Use the second one (http://smashingboxes.github.io/OwlCarousel2) when downloading the packaged release. The difference is the owl-theme class ;).

**Comment by dorothyDorothy** [comment]
Thanks that solves my problem!
Particular thank you for replying so promptly.
