### ISSUE TITLE
lazyLoad without loop: lazyLoad only loads first item after dragging

### ISSUE THREAD

**Issue by IChris2698I** [smashingboxes/OwlCarousel2#1252]
Using the latest version from the Download link on the top left of http://www.owlcarousel.owlgraphic.com/ at the time of this writing, I have an issue with lazyLoad:true, provided I do not specify loop:true (happens whether I leave it out entirely, or specify false).

Specifically, after dragging the carousel with my mouse, or clicking the Next button when I'm using slideBy:'page', only the first element shown is loaded. I drag to a new page and lazyLoad only loads the first image of the newly-shown items.

Picture of the issue (I dragged so item 4 was the first item, which loads it, then dragged back so item 2 was loaded. Item 3 never gets loaded)
![owl-lazyload-missing](https://cloud.githubusercontent.com/assets/17462176/13303212/c9b0954e-db02-11e5-9b1e-287ca2304e1f.png)

For reference, here's my HTML
![lazyload-issue-html](https://cloud.githubusercontent.com/assets/17462176/13303245/0bb83834-db03-11e5-88fe-d36ad200bdbf.png)

and JS
![lazyload-issue-js](https://cloud.githubusercontent.com/assets/17462176/13303255/119f50fc-db03-11e5-9774-e3a254aec334.png)

I'm not sure if I'm doing something wrong or if this is actually an issue, but I've solved it for my own purposes.

In owl.carousel.js, around line 1871, increment position even if clones==0
![handlers-changes](https://cloud.githubusercontent.com/assets/17462176/13303461/695c8f7a-db04-11e5-9a62-b36efbf98787.png)
and in owl.carousel.js, around line 1102, inside Owl.prototype.relative, only run the first .normalize(position) if there are clones
![relative-changes](https://cloud.githubusercontent.com/assets/17462176/13303498/a944f154-db04-11e5-886c-fd8a04caabd2.png)

This should probably be a pull request instead, but I figure an issue is better than nothing. Plus, it might be something I'm doing wrong. Cheers!

**Comment by edgolub** [comment]
The version on http://www.owlcarousel.owlgraphic.com/ is beta2.4.

Try download the version from http://smashingboxes.github.io/OwlCarousel2/ as this is the newest, version beta3 and see if you still have the issue.

**Comment by IChris2698I** [comment]
This does indeed fix my issue. Thanks!

Note for anybody finding this via Google: When going from beta2.4 to beta3, I needed to add the "owl-carousel" class to my carousel. I skipped the theme - I'm using custom prev/next nav and no dots.

I'm also showing the carousel initially (`.owl-carousel` hides it), and I needed to switch that up a bit. Owl Carousel beta2.4 ignored a negative margin-right before load, but beta3 expands into that space. It's a very reasonable change on Owl Carousel's side.

These numbers are designed to work with `.owlCarousel({margin: 15, ...})`
```sass
	&:not(.owl-loaded) {
		// Fake margin until owl-carousel loads
		overflow-y: hidden;
		margin-right: -15px;
		a.book-link { margin-right: 15px; }
	}
```

Now:

```sass
	&:not(.owl-loaded) {
		display: block;
		a.book-link + a.book-link { margin-left: 15px; } // Fake margin until owl-carousel loads
	}
```

**Comment by rapidpace** [comment]
In beta 3 owl.carousel.js baseClass is missing and styles are not visible from owl.carousel.css and hardcoding their style, i.e. to change the class owl-carousel on his own, then when you reload the page reset the scroll position to the very beginning.
Need to add:
1. in Owl.Add Defaults to `baseClass: 'owl-carousel'`
2. `this.$element.toggleClass(this.settings.rtlClass, this.settings.rtl);` change to `this.$element.addClass(this.settings.baseClass).toggleClass(this.settings.rtlClass, this.settings.rtl);`

Or baseClass has finally removed in beta 3?
