### ISSUE TITLE
How to stop the slider to show slides in random order?

### ISSUE THREAD

**Issue by cinghaman** [smashingboxes/OwlCarousel2#1254]
Not sure why but some how my slides keep showing randomly, could'nt find an option to add to the function to stop the randomness
`
( function($) {
	// owl 
	$('.owl-carousel').owlCarousel({
		loop:true,
		responsiveClass:true,
		autoplay:true,
    	autoplayTimeout:5000,
   		autoplayHoverPause:true,
		margin:10,
		singleItem: true,
		stopOnHover: true,
		responsive:{
			0:{
				items:2,
				nav:true,
				loop:true
			},
			600:{
				items:3,
				nav:true,
				loop:true
			},
			1000:{
				items:3,
				nav:true,
				loop:true
			}
		},
		onInitialized: function() {
            if ($('.owl-carousel').children().length == 1) {
                 $('.owl-carousel').trigger('autoplay.stop.owl');
            }
        }
		
	});
`

**Comment by boudga** [comment]
did you figure out how to stop it from randomizing?

**Comment by cinghaman** [comment]
I re uploaded my slides and it worked
