### ISSUE TITLE
What is `-webkit-backface-visibility: hidden` for?

### ISSUE THREAD

**Issue by Globegitter** [smashingboxes/OwlCarousel2#297]
I am using Owl Craousel to display a couple of logos. When I add them to the site they look fine like here:
![capture decran 2014-07-14 a 11 07 47](https://cloud.githubusercontent.com/assets/2580254/3569405/d1428fdc-0b3e-11e4-82ab-65fd376698ef.png)

As soon as I add the `owl-carousel` class though and the images get transformed to the carousel the logo looks like this:
![capture decran 2014-07-14 a 11 09 04](https://cloud.githubusercontent.com/assets/2580254/3569437/40cb40e2-0b3f-11e4-9887-829ae757d8c8.png)

And I can't seem to figure out why.

Edit: Seems I found the issue: `-webkit-backface-visibility: hidden` If I remove this line in the CSS Inspector the image looks fine again. Is there any reason why this property is applied or can this be safely removed/overwritten?

**Comment by KennethAshley** [comment]
Stale issue. If this issue continues please read our [bug reports guide](https://github.com/smashingboxes/OwlCarousel2/#bug-reports).
