### ISSUE TITLE
Preserve 3D bug in Chrome

### ISSUE THREAD

**Issue by webdesignhertfordshire** [smashingboxes/OwlCarousel2#435]
The problem is discussed here:
http://stackoverflow.com/questions/10755440/why-does-webkit-transform-style-preserve-3d-make-some-divs-disappear

JSbin here:
http://jsbin.com/gaqowejewoba/1/edit

Problem was resolved by removing:
```
-webkit-transform-style: preserve-3d;
```
From
```
.owl-carousel .owl-item img { }
```
From the main CSS file and removing the line
```
.owl-carousel .owl-item img {
  transform-style: preserve-3d;
}
```
From the Lazy Load Plugin section of the CSS

**Comment by KennethAshley** [comment]
Please upgrade to the newest version of Owl Carousel, released today, and re-open this issue if it persists.
