### ISSUE TITLE
Nesting carousels

### ISSUE THREAD

**Issue by wonderment** [smashingboxes/OwlCarousel2#466]
http://jsfiddle.net/eqbL6vLb/34/

Is there any way to separate the two carousel objects to prevent the parent carousel from overwriting the child's carousel? I.e. can they operate independently with the current markup in that fiddle?

I would like the main slider to operate as usual with a 3-item mini carousel shown in the corner per each slide.

I wasn't sure whether this constitutes as an issue worth writing here because of the results or if it's more appropriate on stackoverflow.

**Comment by KennethAshley** [comment]
@wonderment are you still having an issue with this?
