### ISSUE TITLE
SemVer

### ISSUE THREAD

**Issue by n00dl3** [smashingboxes/OwlCarousel2#469]
Hi,
first of all, thank you for your work, it's a very interesting piece of software.
I am using Owl carousel 2 in one of my project, and like any other external library, i'm using bower to manage versions. I have built a plugin to synchronize 2 galleries and noticed that your software didn't comply to the semantic versioning specification. That makes it very hard to maintain compatibility between the plugin and owl-carousel2 via a package manager (like bower in our case). In deed, in a previous version we could access the jQuery element from the plugin via carousel.$element and now we have to use carousel.dom.el (or maybe carousel.dom.$el).
I know owl caousel v2 is in a beta state but maybe using the semantic versioning spec may help people like me.
Thank you for the work.

**Comment by greg5green** [comment]
This is happening now. :+1:
