### ISSUE TITLE
Single side full width

### ISSUE THREAD

**Issue by mactedder** [smashingboxes/OwlCarousel2#515]
I want to use Owl Slider 2 as a 'responsive' top of page slider for a full width banner.

This works fine when I have 2 or more images but when I only have 1 image the banner disappears?

What am I doing wrong?

**Comment by joeyjoejoejr** [comment]
Can someone verify that this is still an issue?

**Comment by KennethAshley** [comment]
Please upgrade to the newest version of Owl Carousel, released today, and re-open this issue if it persists.
