### ISSUE TITLE
Callbacks does not pass parameters

### ISSUE THREAD

**Issue by zlatko0o** [smashingboxes/OwlCarousel2#526]
Callbacks does not pass parameters. On minified version this.settings[f].apply(this,g) this should be this.settings[f].apply(this,[g])

**Comment by greg5green** [comment]
This issue has been fixed by #271 and will be in the next version. If you need a fix before we get this published, you can build from source yourself using Grunt and the `dist` task as described in the README

**Comment by rudzboy** [comment]
Wonderful ;) Thx
