### ISSUE TITLE
Owl Carousel is not working in chrome browser

### ISSUE THREAD

**Issue by sunrayravi** [smashingboxes/OwlCarousel2#527]
not sure why but the carousel is not at all working in the chrome browser.
Autoplay, swipe nothing seems to work.

**Comment by joeyjoejoejr** [comment]
Can someone verify that this is still an issue?

**Comment by KennethAshley** [comment]
Please upgrade to the newest version of Owl Carousel, released today, and re-open this issue if it persists.
