### ISSUE TITLE
IE8 error

### ISSUE THREAD

**Issue by claudchan** [smashingboxes/OwlCarousel2#533]
Hi,
I got an error on testing in IE8. 

![ie8-debug](https://cloud.githubusercontent.com/assets/1639056/4471880/efe306d0-493f-11e4-8acd-a645744ecb17.jpg)

**Comment by joeyjoejoejr** [comment]
Can someone verify that this is still an issue?  Are we supporting IE8?

**Comment by KennethAshley** [comment]
Please upgrade to the newest version of Owl Carousel, released today, and re-open this issue if it persists.
