### ISSUE TITLE
Owl.to triggers Error 

### ISSUE THREAD

**Issue by anteksiler** [smashingboxes/OwlCarousel2#537]
I am getting the following error:
Uncaught TypeError: Cannot read property 'start' of undefined 

on line:
$.proxy(this._overrides.to, this._core)(this._pages[((position % length) + length) % length].start, speed);

**Comment by sibinx7** [comment]
It has 3rd parameter which is not in document, I am using 2.0.0 version

Navigation.prototype.to = function(position, speed, standard) {

Set [position, speed, standard]

I set standard as true/false/1/0

It worked in my slider
