### ISSUE TITLE
Page structure crashes after changing page orientation or browser width

### ISSUE THREAD

**Issue by george-of-314** [smashingboxes/OwlCarousel2#545]
I'm using OwlCarousel 2 beta for mobile version of my website. Quantity of showed images depends of screen width. After page orientation change I want to reinit owlCarousel with new value of items. 
After orientation change (or window width change) it breaks the page layout. Here's JSFiddle: http://jsfiddle.net/wgj7y86y/1/

Any ideas, how to fix this?

**Comment by george-of-314** [comment]
Hello!

I made it like this:

$(document).ready(function() {      var owl = $("#owl-demo");      if
(screen.availWidth < $(window).width()) {        var sWidth =
screen.availWidth / 300;      } else {        var sWidth =
$(window).width() / 300;      }      var qua = Math.floor(sWidth);
 if (qua < 1) { qua = 1; }      owl.owlCarousel({        autoPlay:
false,        smartSpeed: 600,        nav: true,        navText:
['<img src="/images/larrow.png" width="30">','<img
src="/images/rarrow.png" width="30">'],        pagination: false,
  responsive:{            0:{                items:1 // small
viewports show 1            },            400:{                items:2
// 600px - 999px viewports show 2            },            700:{
         items:3 // 600px - 999px viewports show 3            },
     1000:{                items:4 // 1000-1299px show 4            },
           1300:{                items:5 // 1300px - 1599px viewports
show 5            },            1600:{                items:6 //
1600px and up viewports show 6            }        }      });
function arrows(event) {        var item      = event.item.index;
  var totitems = event.item.count;        var color =
$('.item[rel="'+item+'"]').first().attr('rev');
$('#color').val(color);        if (item + qua === totitems) {
$('.owl-next').css('opacity',0.3);        } else {
$('.owl-next').css('opacity',1);        }        if (item === 0) {
     $('.owl-prev').css('opacity',0.3);        } else {
$('.owl-prev').css('opacity',1);        }      }
owl.on('changed.owl.carousel', arrows);
owl.on('resize.owl.carousel', arrows);
$('#color').on('change',function (){        var color = $(this).val();
       var first = $('.item[rev="'+color+'"]').first().attr('rel');
    $("#owl-demo").trigger('to.owl.carousel', [first, 200, true]);
 });    });



2014-12-31 7:56 GMT+02:00 Luke Branch <notifications@github.com>:

**Comment by KennethAshley** [comment]
Please upgrade to the newest version of Owl Carousel, released today, and re-open this issue if it persists.
