### ISSUE TITLE
Second row with autoWidth:true,

### ISSUE THREAD

**Issue by webspilka** [smashingboxes/OwlCarousel2#550]
When owl-item.width > window.width - everything works as expected
But when resize window to
owl-item.width < window.width 
and refresh page, Carousel photo shows in two lines
Video: http://youtu.be/FaLJB1cKSvY
Screenshot:
![pmcu_owl](https://cloud.githubusercontent.com/assets/1138069/4589602/fa523268-5055-11e4-838b-b1435f996fdf.png)

my code is

$(document).ready(function() {
		$('.owl-carousel').owlCarousel({
		    margin:10,
		    loop:true,
		    nav: true,
		    dots: false,
		    autoWidth:true,
		    navText: ['<span class="glyphicon glyphicon-chevron-left"></span>','<span class="glyphicon glyphicon-chevron-right"></span>'],
		    stagePadding: 55,
		    items:5
		})
	});
	</script>

**Comment by joeyjoejoejr** [comment]
Closed as duplicate
