### ISSUE TITLE
callback is not working 

### ISSUE THREAD

**Issue by phuyem** [smashingboxes/OwlCarousel2#567]
owl.owlCarousel({
        items : 3,
        lazyLoad : true,
        loop:true,
        nav : true,
        navText	: ["<",">"],
         onDragged: function(event) {
		     
		}      
      });

event is undefined.

I found a work-around: in Owl.prototype.trigger, change apply() to call() or  simply 

     this.settings[handler] (this, event);

**Comment by joeyjoejoejr** [comment]
Looks like a duplicate of this issue: #526
