### ISSUE TITLE
startPosition not working

### ISSUE THREAD

**Issue by camilonova** [smashingboxes/OwlCarousel2#569]
The ```startPosition``` parameter is not working.

Somehow the javascript file from the documentation is different from the one installed using bower.

Diff here: https://www.diffchecker.com/v0k2fnlp

**Comment by joeyjoejoejr** [comment]
@rob-m-andrews can you answer this question, and-or straighten this out.

**Comment by camilonova** [comment]
We'll this is not a question, is a 5 months old bug.

**Comment by joeyjoejoejr** [comment]
It looks like it's not actually a bug on develop, based on #182

**Comment by camilonova** [comment]
@joeyjoejoejr I'm still seeing this bug on the version installed using bower.
