### ISSUE TITLE
Release 2.0.0-beta.2.4

### ISSUE THREAD

**Issue by camilonova** [smashingboxes/OwlCarousel2#577]
Make a tag or a release for version 2.0.0-beta.2.4 so bower can identify the version.

https://help.github.com/articles/creating-releases/

**Comment by joeyjoejoejr** [comment]
@rob-m-andrews This is related to the bower version issues.

**Comment by camilonova** [comment]
@joeyjoejoejr You just need to create a tag in the repo.

**Comment by ceesgeene** [comment]
Yes please

**Comment by redaxmedia** [comment]
Please create a tag, god damn it...

**Comment by greg5green** [comment]
This has [happened](https://github.com/smashingboxes/OwlCarousel2/releases/tag/2.0.0-beta.2.4). And @redaxmedia, please keep it professional.

**Comment by ceesgeene** [comment]
Thanks @greg5green
