### ISSUE TITLE
calculate width .owl-stage

### ISSUE THREAD

**Issue by JarekWichrowski** [smashingboxes/OwlCarousel2#582]
Width in .owl-storage is to small... and last slide jumps down

http://csshtml.pl/galeria/

+1px and is ok

**Comment by diede-dertig** [comment]
Why was this issue closed? This has not been fixed, has it?

**Comment by CoryFoy** [comment]
@diede-dertig I'm guessing because there were workarounds listed above. If that's a mistake, don't hesitate to reopen it and let us know (or even shoot a PR!)

**Comment by mgntrn** [comment]
For me the mentioned workaround didn't work as expected, but this worked for me:
```javascript
function recalcCarouselWidth(carousel) {
    var stage = carousel.find('.owl-stage');
    stage.width(Math.ceil(stage.width()) + 1);
}

$(window).on('resize', function(e){
    recalcCarouselWidth($('.owl-carousel'));
}).resize();

$('.wm-carousel').on('refreshed.owl.carousel', function(event) {
    recalcCarouselWidth($('.owl-carousel'));
});
````

**Comment by naeim** [comment]
Had This problem.
for me its happened because  slide loaded on display:none div, so width didnt calculate on load.
manage to hide div after slider loaded.
hide  wrapper with css   .wrapper{display:none}   
add class"js" to body after  owlCarousel.:

jQuery("body").addClass("js");
.js .wrapper{ display: none; }

**Comment by imolorhe** [comment]
I am also currently facing this issue. This issue looks like something that should be solved with the plugin itself, not using workarounds. It affects the core functionality of this plugin.

**Comment by esch8048** [comment]
I found that I ran into this issue only when I was setting widths of my individual carousel items to a non-integer value - rounding widths up or down solved the issue for me.

**Comment by Roy-Orbison** [comment]
I had this issue on a site (where I cannot update/modify Owl) and fixed it with this CSS:

```CSS
body .owl-stage {
    width: auto !important;
    white-space: nowrap;
}
body .owl-stage .owl-item {
    position: static;
    float: none;
    display: inline-block;
    vertical-align: top;
}
```

As commented on issue #424.

**Comment by viveksaroch** [comment]
if @mgntrn  code not work then use this code i made some changes in it.
    function recalcCarouselWidth(carousel) {
        var stage = carousel.find('.owl-stage');
        stage.width(Math.ceil(stage.width()) + 1);
    }

    $(window).on('resize', function(e){
        recalcCarouselWidth($('.textures-carousel'));
    }).resize();

    $('.textures-carousel').on('refreshed.owl.carousel', function(event) {
        setTimeout(function(){
            recalcCarouselWidth($('.textures-carousel'));
        }, 200);
    });

**Comment by viveksaroch** [comment]
i am sure that it would be work perfectly

**Comment by KalterDK** [comment]
> if @mgntrn code not work then use this code i made some changes in it.
> function recalcCarouselWidth(carousel) {
> var stage = carousel.find('.owl-stage');
> stage.width(Math.ceil(stage.width()) + 1);
> }
> 
> ```
> $(window).on('resize', function(e){
>     recalcCarouselWidth($('.textures-carousel'));
> }).resize();
> 
> $('.textures-carousel').on('refreshed.owl.carousel', function(event) {
>     setTimeout(function(){
>         recalcCarouselWidth($('.textures-carousel'));
>     }, 200);
> });
> ```

Thank you very much, it's best solution for me.
