### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by dmcclintock** [smashingboxes/OwlCarousel2#584]
The links pointing to the "Next Step" at the end of both the [Options][1] and the [Classes][2] pages under "API" appear to be missing the "api-" prefix in the filename portion of the uri, resulting in a 404.

[1]: www.owlcarousel.owlgraphic.com/docs/api-options.html
[2]: www.owlcarousel.owlgraphic.com/docs/api-classes.html

**Comment by rob-m-andrews** [comment]
@danielsmcclintock I am fixing this issue now. Thank you.

**Comment by greg5green** [comment]
This was fixed by #246 and #247
