### ISSUE TITLE
One dot

### ISSUE THREAD

**Issue by nepster-web** [smashingboxes/OwlCarousel2#585]
Hi!
I'm sorry, I do not know English ( use https://translate.google.ru)

my problem:
There are 5 items of 5 items:
http://clip2net.com/s/jcy0bj

and dot on display.

why does the dot not hidden?

**Comment by joeyjoejoejr** [comment]
Can you post the image of the the issue you are seeing again?

**Comment by nepster-web** [comment]
Image are deleted. Sorry I can not restore image. it was a long time ago.
