### ISSUE TITLE
Wrong event listener?

### ISSUE THREAD

**Issue by Lemmork** [smashingboxes/OwlCarousel2#589]
Hi,

I have a strange behaviour with the triggerable events in owl.carousel2.
In my slides there are images, which are changed by foundation.interchange.js. This script triggers a "replace" event on the img-object.
I'm not sure why, but owl reacts on this event even it is not assigned to the owl wrapper. If I read the code right, owl should react only on "replace.own.carousel" and not on "replace".

Removing replace from the triggerable events it solves my problem.

Regards

**Comment by joeyjoejoejr** [comment]
Closed as a duplicate.  We'll have to get around renaming the events soon.
