### ISSUE TITLE
Autoplay in latest development code not working

### ISSUE THREAD

**Issue by mtbitcoin** [smashingboxes/OwlCarousel2#594]
Hi

I just tested the autoplay at https://github.com/OwlFonk/OwlCarousel2/archive/develop.zip and it looks like it is not working. I understand that this is development code, but just a heads up just incase this was missed

looks related to https://github.com/OwlFonk/OwlCarousel2/issues/495

**Comment by apeitup** [comment]
try using 

autoplay: true,

instead of autoPlay: true,
