### ISSUE TITLE
Class list link is 404

### ISSUE THREAD

**Issue by ikixxx** [smashingboxes/OwlCarousel2#606]
http://www.owlcarousel.owlgraphic.com/docs/classes.html

**Comment by joeyjoejoejr** [comment]
This is a know issue, we are currently working on getting the website and docs sorted out.

**Comment by alsokolov** [comment]
On this page [ http://www.owlcarousel.owlgraphic.com/docs/api-options.html] still this old href left. ("Class list"  near footer).
I think should be http://www.owlcarousel.owlgraphic.com/docs/api-classes.html like in sidemenu.
