### ISSUE TITLE
Error in chrome

### ISSUE THREAD

**Issue by richa-gupta** [smashingboxes/OwlCarousel2#613]
Uncaught TypeError: boolean is not a function in chrome.
But it is working fine for firefox

**Comment by kajimura-dg** [comment]
When I use jquery 1.10.1, it is working on Chrome.

**Comment by jhongstore** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

dcjae@naver.com 님께 보내신 메일 <Re: [OwlCarousel2] Error in chrome (#613)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
