### ISSUE TITLE
Clonning and dragging carousel items

### ISSUE THREAD

**Issue by gal007** [smashingboxes/OwlCarousel2#614]
Hi! I'm trying to clone the carousel items to make them draggables, but I coudn't do it so I'm asking any kind of help (code, ideas, examples, docs).   

I made a demo in order to clarify what I'm trying to do (I want the same behaviour as the orange div):
http://jsfiddle.net/hjug75p1/18/

Thanks in advance!

**Comment by joeyjoejoejr** [comment]
Cool idea
