### ISSUE TITLE
owlcarousel video not working

### ISSUE THREAD

**Issue by tiuscia** [smashingboxes/OwlCarousel2#623]
Hi guys,

owl carousel (video) is not working <img src="http://www.tiuscia.com/owl.png"> .
I tried to remove jquery but it's not working anyway. Do you have any suggestions?
(if you want check the code login/password: support)

Thanks a lot
Tiu

**Comment by joeyjoejoejr** [comment]
If this is still an issue could you add the information outlined here:
https://github.com/smashingboxes/OwlCarousel2#bug-reports
