### ISSUE TITLE
owl-carousel and owl-theme classes not added to the DOM

### ISSUE THREAD

**Issue by brunorios1** [smashingboxes/OwlCarousel2#627]
Hi,

My carousels only works correctly if I manually adds the owl-carousel and owl-theme classes to the markup.
I'm doing this:

Html:
http://paste2.org/E4fZXanw

Js:
http://paste2.org/w9bVMMjm

And the result:
http://paste2.org/Nds5YgsH

Thanks!

**Comment by joeyjoejoejr** [comment]
This is intended.  See the docs: http://owlgraphic.com/owlcarousel/#how-to

**Comment by lmeurs** [comment]
For the record: version 2.0.0-beta.2.4 (http://www.owlcarousel.owlgraphic.com/download/owl.carousel.zip) automatically adds the base and theme classes, the most recent version from the GitHub repository does not.

**Comment by MohammadDayeh** [comment]
in the version 2.0.0-beta.3  themeClass and baseClass options are removed. It would be good to have them back again. Sometimes you need to apply different themes using the options.
