### ISSUE TITLE
RTL Support broken when using SCSS

### ISSUE THREAD

**Issue by magic-77** [smashingboxes/OwlCarousel2#635]
There is an issue with Support for RTL.
In "owl.caroussel.scss" at Line 94, and Line 98 change from
`
    .owl-rtl {
      direction: rtl;
    }
`
`
    .owl-rtl .owl-item {
      float: right;
    }
`
to
`
    &.owl-rtl {
      direction: rtl;
    }
`
`
    &.owl-rtl .owl-item {
      float: right;
    }
`
then it works fine again :-)
Greets
Marek

**Comment by joeyjoejoejr** [comment]
Appears to be fixed on develop
