### ISSUE TITLE
Slider inside iframe problem

### ISSUE THREAD

**Issue by mekshq** [smashingboxes/OwlCarousel2#637]
First of all thank you for your wonderful slider - it really rocks.

We are building WordPress themes and we are using your slider a lot but there is one issue that I noticed in several themes, not only ours.

When I try to load site via iframe on iOS devices (iPhone/iPad) everything breaks...

Here are several examples:

http://themeforest.net/item/words-personal-blog-theme/full_screen_preview/9642505
http://themeforest.net/item/gridstone-elegantly-built-for-blogger/full_screen_preview/9413936
http://demo.mekshq.com/?theme=voice

Sorry for links, I don't have intention of promoting these themes, I just want to solve this problem together.

Thank you 
Meks Team

**Comment by KennethAshley** [comment]
Please upgrade to the newest version of Owl Carousel, released today, and re-open this issue if it persists.
