### ISSUE TITLE
Avoid flash of unstyled content (FOUC)

### ISSUE THREAD

**Issue by lmartins** [smashingboxes/OwlCarousel2#640]
Is there any recommended way to avoid this issue while using OWL?

Thanks.

**Comment by KennethAshley** [comment]
Hello!

I'm not entirely sure what this issue is about. Please read our [bug reports guide](https://github.com/smashingboxes/OwlCarousel2/#bug-reports) if it's a bug, and read the [contributing guide](https://github.com/smashingboxes/OwlCarousel2/#contributing) for how to create pull requests.
