### ISSUE TITLE
SASS Namespacing

### ISSUE THREAD

**Issue by justinanastos** [smashingboxes/OwlCarousel2#647]
All mixins and variable names in SASS are global. ([source](https://gist.github.com/matyus/4339721#file-_scope-scss)). Therefore, all variable names and mixins need to be namespaced to the plugin. For example, you will get sass compilation errors if you include bourbon.io and the owl theme files since they define conflicting `transition` and `transform` mixins.

Also, the keyframes defined in `owl.animation.scss` should be namespaced so they don't override other fadeOut animations.

**Comment by joeyjoejoejr** [comment]
@jonmilner This looks like an issue that's in your wheelhouse.
