### ISSUE TITLE
Plans for LESS support?

### ISSUE THREAD

**Issue by CFXd** [smashingboxes/OwlCarousel2#650]
I noticed OwlCarousel2 includes SASS source files. Are there any plans (or enough demand) for LESS source files too? I could work on a PR if there's a consensus...

**Comment by pribilinskiy** [comment]
+1
@nsams Maintainers of frameworks like Bootstrap don't bother having a PITA

**Comment by JulienMelissas** [comment]
Yo wazzap @CFXd!
:+1: for this

**Comment by gasp10** [comment]
i've already re-write and make a less version of the base css carousel, it's not that hard but...
+1

**Comment by joeyjoejoejr** [comment]
@eparisio Would you like to open a pull request with the less rewrite.

**Comment by eparisio** [comment]
sorry but i don't understand how to make it.
i fork it grom the main button fork and create a my local repo, than i go inside it and hit clone to desktop.
I make the changes and commit but when i try to make a sync from windows panned it say i have no privilage, and if i try to make a pull request from the windows pannel it say that i'm on the same branch.

What i'm doing wrong? i'm following exactly what this guide say:
https://guides.github.com/activities/forking/

**Comment by eparisio** [comment]
Made pull request for less support
