### ISSUE TITLE
SASS file names and CSS generation

### ISSUE THREAD

**Issue by numediaweb** [smashingboxes/OwlCarousel2#661]
Searching for the easiest/quickest way to include the plugin into existing projects, I would suggest renaming the partial files to be compliant with [SASS standards on partials](http://sass-lang.com/guide#topic-4), that is, the name should be proceeded with underscore "_"; 
* _owl.animate.scss
* _owl.lazyload.scss
* _owl.video.scss
* owl.theme.default.scss
* ..

Say I have a project with SASS and need to include the Owel themes/styles inside my app.css file, I would just call;
```SASS
@import "owl.animate";
@import "owl.lazyload";
```
Because the way the styles are now generated is a bit.. complex and unorganized? I think, since we; use **sass** to compile all the `src/scss/` files and then use **concat** to assemble those files into `dist/assets/owl.carousel.css`.

**Comment by mikehdt** [comment]
What I do is put anything not written by me into a /vendor subfolder, and then the project's name under that. I also use a number of other folders to keep my own stuff organised. I'd wonder about my sanity if I kept every single Sass file in a project inside the one flat folder ;)

**Comment by numediaweb** [comment]
true! you can close this ticket thanks :)
