### ISSUE TITLE
How can disable previous/next in OwlCarousel2 if there aren't enough items to scroll.?

### ISSUE THREAD

**Issue by sanjukanwasi** [smashingboxes/OwlCarousel2#662]
Is there a way to disable the previous and next links if there aren’t enough items to scroll?

For example: http://truewest.nextmp.net/special-programs these galleries allow for 4 items (desktop), there are only 4 items in this gallery but the buttons to pagination still appear, but should be disabled.

**Comment by dnndiva** [comment]
Same for dots. Navigation should only show when needed. Just like the version 1. It was great! Please bring it back. =)

**Comment by kompolom** [comment]
+1

**Comment by wgdes** [comment]
There should be a "disabled" class added to the prev/next links automatically. You should be able to use CSS to hide them as needed.

**Comment by kompolom** [comment]
@wgdes Thanks! 
Solution is add it to config:

    loop: false,
    navRewind: false,

**Comment by joeyjoejoejr** [comment]
This is a duplicate.  Check the open feature requests.
