### ISSUE TITLE
Autoplay doesn`t work on Samsung Galaxy Tab

### ISSUE THREAD

**Issue by nwnet** [smashingboxes/OwlCarousel2#664]
Autoplay doesn`t work on Samsung Galaxy Tab 3 - it moves one time and then stops forever.

Was tested on Dolphin and Default browsers

**Comment by jhongstore** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

dcjae@naver.com 님께 보내신 메일 <[OwlCarousel2] Autoplay doesn`t work on Samsung Galaxy Tab (#664)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by KennethAshley** [comment]
@nwnet are you still having this issue?

**Comment by nwnet** [comment]
Now everything is ok
