### ISSUE TITLE
TypeError: items[clones[(clones.length - 1)]] is undefined

### ISSUE THREAD

**Issue by jsmad** [smashingboxes/OwlCarousel2#667]
When my owl carousel has only one img item, the script fails with the following error:

```
TypeError: items[clones[(clones.length - 1)]] is undefined
```

my html:
```html
<div id="itemcarousel" class="owl-carousel">
	<img class="owl-lazy" data-src="media/somefile.png" alt="title">
</div>
```

my javascript:
```javascript
	$('#owlcarousel').owlCarousel({
		items: 1,
		loop: true,
		nav: false,
		dots: false,
		lazyLoad: true,
		autoplay: true,
		autoplayHoverPause: true,
		responsive:{
			0:{ items: 1 }
		}
	});
```

**Comment by jhongstore** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

dcjae@naver.com 님께 보내신 메일 <[OwlCarousel2] TypeError: items[clones[(clones.length - 1)]] is undefined (#667)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by jsmad** [comment]
I foud this temporary solution, I am not sure if it breaks anything else, but it seems to work for me and my one image carousels.

```diff
--- jquery.owlcarousel.js.orig	2015-01-11 18:43:39.152186007 +0200
+++ jquery.owlcarousel.js	2015-01-11 18:43:45.973186001 +0200
@@ -286,9 +286,9 @@
 			var i, n,
 				clones = this._clones,
 				items = this._items,
-				delta = this.settings.loop ? clones.length - Math.max(this.settings.items * 2, 4) : 0;
+				delta = this.settings.loop ? clones.length - Math.max(this.settings.items * 2, 3) : 0;
 
-			for (i = 0, n = Math.abs(delta / 2); i < n; i++) {
+			for (i = 0, n = Math.floor(Math.abs(delta / 2)); i < n; i++) {
 				if (delta > 0) {
 					this.$stage.children().eq(items.length + clones.length - 1).remove();
 					clones.pop();
```

**Comment by jhongstore** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

dcjae@naver.com 님께 보내신 메일 <Re: [OwlCarousel2] TypeError: items[clones[(clones.length - 1)]] is undefined (#667)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by ChenRoth** [comment]
having the same issue here:

if there's a single image, and the loop parameter is true, the code breaks at line 299 (in v2.0.0):

"this.$stage.append(items[clones[clones.length - 1]].clone().addClass('cloned'));"

the case is that items is an array of only one item, while the loop runs for index < 2, resulting in an illegal reference

here's a minimal test case:

http://jsfiddle.net/p69xkjtz/3/

I've also tried this in the latest develop branch - there's no exception, but the carousel shows a blank element, and allows you to loop through, cloning more blank elements.

**Comment by greg5green** [comment]
This is fixed in the newest version of OwlCarousel2. You can grab it from http://smashingboxes.github.io/download/owl.carousel.2.0.0-beta.3.zip or bower
