### ISSUE TITLE
How to disable scroll for someone #id in carousel?

### ISSUE THREAD

**Issue by 6pm** [smashingboxes/OwlCarousel2#671]
I need install event  on swipe from block in carousel. How to disable scroll/swipe in someone elements in owlCarousel?

**Comment by jhongstore** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

dcjae@naver.com 님께 보내신 메일 <[OwlCarousel2] How to disable scroll for someone #id in carousel? (#671)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by KennethAshley** [comment]
Hello!

I'm not entirely sure what this issue is about. Please read our [bug reports guide](https://github.com/smashingboxes/OwlCarousel2/#bug-reports) if it's a bug, and read the [contributing guide](https://github.com/smashingboxes/OwlCarousel2/#contributing) for how to create pull requests.
