### ISSUE TITLE
Applying angularjs ng-repeat to owl-carousel

### ISSUE THREAD

**Issue by Fabii23** [smashingboxes/OwlCarousel2#674]
I'm running into an issue where whenever the ng-repeat directive is applied to carousel the items are stacked vertically instead of being layout horizontally.

If I leave out ng-repeat and use static items then it works as it should.

Is there a directive I can write and apply to owl-carousel to maintain the layout?

Also what is about ng-repeat that is causing the carousel to break?

Is angular somehow stripping the owl-carousel classes applied to the carousel?

**Comment by kisonay** [comment]
I too am interested in this. I actually have it working in one spot but cannot get a second directive call working on the same page.

I read somewhere that Owl2 was going to work with Angular. Do we need to do anything special?

**Comment by itsthatguy** [comment]
This actually looks like an [angular-filter](https://github.com/a8m/angular-filter) issue.

**Comment by jeffpannone** [comment]
Have you tried the [angular-imagesLoaded](https://github.com/homerjam/angular-images-loaded) ? It worked for my implementation of owl/angular. 

```javascript
$scope.imgLoadedEvents = {

	always: function(instance) {
	   // Do stuff always
	},
	done: function(instance) {
		// Do stuff if images load

		// Owl intialize
		$(document).ready(function(){
		  $(".owl-carousel").owlCarousel();
		});
	},
	fail: function(instance) {
	   // Do stuff if images fail to load
	}

};
```

**Comment by KennethAshley** [comment]
Closed due to stale issue.
