### ISSUE TITLE
Bug on Chrome under cms

### ISSUE THREAD

**Issue by Alyor** [smashingboxes/OwlCarousel2#675]
Hi, I'll try this plugin under thélia cms it work under IE, FF, Saphari perfectly but under Chrome not running.

I used jquery 1.8.3.min, i allready tried the old and last version nothing change.

Here the slider link working on the bot right side:
http://nhoya.com/?fond=test

I'll try another slider in same time.
Hope some one can light me, thanks.

**Comment by gasp10** [comment]
i see a big html file in the owl.carousel.js that broke everiting i think.
and you load the min file too.

**Comment by Alyor** [comment]
Thanks, I'll try your tip but nothing change also I uploaded the files again nothing change too but it work on IE FF and Saphari, the old version of owl carousel work fine with chrome so the version is in beta I think something missing in the owl.carousel.js to be compatible with chrome for a cms like thelia.

And this link with the old version helpfull for fade effect on chrome work perfectly for 1 slide https://raw.githubusercontent.com/iamphill/OwlCarousel/a2bcc904908ae1417d01a85bf024c7c88c2f95ee/owl-carousel/owl.carousel.min.js

source: http://stackoverflow.com/questions/24911447/owl-carousel-fade-effect-not-working

**Comment by eparisio** [comment]
$(".owl-demo").owlCarousel({

you are using a class reference but your owl element have an id reference

    $("#owl-demo").owlCarousel({

**Comment by Alyor** [comment]
I change the code to the class for use it on other page. I give up the debug actually it seems the owner give up his plugin so i deal with it now :/

**Comment by KennethAshley** [comment]
@Alyor are you still having this issue?
