### ISSUE TITLE
Wrong width problem

### ISSUE THREAD

**Issue by mosesmalone** [smashingboxes/OwlCarousel2#677]
Hi :)

I really like the new version, but I'm having trouble with the correct width of the elements on first initialization.
See here: http://gd3.de/owl.carousel.2.0.0-beta.2.4/

When I resize the window it works perfectly.

**Comment by mosesmalone** [comment]
When my cache is empty, it works fine the first time.
But when I press F5 to reload the page, the width is off again.
(Just noticed that)

**Comment by leandroruel** [comment]
it works for me, without problems

**Comment by alteredstudio** [comment]
I've seen this issue only in Safari. The question is is it Safari or Owl?

**Comment by mosesmalone** [comment]
I have that problem in FF and Chrome.
As mentioned before, after refresh.

**Comment by mosesmalone** [comment]
I switched to Slick carousel now, as it can do infinite scrolling while being responsive (showing different amount of slides depending on screen-width). There are issues with that slider as well, but fewer :)

**Comment by alteredstudio** [comment]
@mosesmalone Yeah I'm using that one too. It's hard to round corners and they have some funky height issues if you do not set a height but no perfect product yet I guess.
