### ISSUE TITLE
Mouse Wheel 

### ISSUE THREAD

**Issue by meroomaher** [smashingboxes/OwlCarousel2#683]
How can i stop the mouse wheel control once I get the last slide ?

( I made a vertical slider with three slides and  i would like once i get the last slide the owlCarousel2 will give back the control with the browser scroll to scroll down again )

**Comment by meroomaher** [comment]
that is my JS Code 

 var owl = $('#Intro');
    var items;
    var item;
    owl.owlCarousel({

        animateOut: 'fadeOutUp',
        animateIn: 'fadeInUp',
        items: 1,
        mouseDrag: false,
        onChanged: callback


    });

    function callback(event) {
        items = event.item.count;     // Number of items
        item = event.item.index;     // Position of the current item
    }

    owl.on('mousewheel', '.owl-stage', function(e) {
        if (e.deltaY > 0) {
            owl.trigger('prev.owl');
            e.preventDefault();
        } else {


            owl.trigger('next.owl');
            if (items != item) {
                e.preventDefault();
            }
        }



    });

**Comment by gasp10** [comment]
hmm

     if (e.deltaY > 0) {
        owl.trigger('prev.owl');
        e.preventDefault();
>    } else  if( items != item ) {

        owl.trigger('next.owl');
        if (items != item) {
            e.preventDefault();
        }
    }

you can try something similar.
item or item-1 should work, you must debug.
