### ISSUE TITLE
Project Abandoned [not anymore]

### ISSUE THREAD

**Issue by leandroruel** [smashingboxes/OwlCarousel2#685]
bad news:
Announcement.

Hello everyone.

For a past few months i was out of the work and i could not maintain Owl. At the moment im in situation that i dont have time to work on this project anymore and im changing direction of my future carrer.

I would like to give that project with all assets and rights to some reliable person who can finish and maintain the code. If you are interested then please give me a shout: zly.ojciec@gmail.com

Thank you.

**and**

after this, this repository was transferred to **smashing boxes** look their website

**Comment by lpgray** [comment]
Where r u going? To be a singer?

**Comment by leandroruel** [comment]
it's from project author OwlFonk: https://github.com/OwlFonk/OwlCarousel2/blob/develop/README.md

**Comment by HybridSolutions** [comment]
Dam! That's why I don't like open Source! :(

**Comment by proov** [comment]
I'm sad :(

I wish you all the best for your future career @leandroruel :)

**Comment by noelmcg** [comment]
Would it not be possible for us to collectively keep this going?

Take on a bit more responsibility, maybe?!

On 28 January 2015 at 17:45:24, PREVOST Sylvain (notifications@github.com) wrote:

I'm sad :(

I wish you all the best for your future career @leandroruel :)

**Comment by twistedpixel** [comment]
This deeply saddens me :(

**Comment by DigitalLandes** [comment]
:(

**Comment by leandroruel** [comment]
guys, hahaha, i simply copy and paste here the words from original author, it's not me, its OwlFonk...

and... HEY!!! the repository changed to another person! O.o

**Comment by leandroruel** [comment]
this project is now of smashing boxes!

**Comment by eparisio** [comment]
oh very good, this is one of the best carousel out there it to bad if no one can maintanance it.
We will see the project that they will have about it, the main goal actually is to fix the actual remaining bug, than if they develop new functionality  will be a big step forward for the project.

**Comment by proov** [comment]
I'm glad to read this :)

I wish to be able to contribute too but i'm a webdesigner, not a developper ^^

**Comment by joeyjoejoejr** [comment]
We are glad to be maintaining it!  Please do continue to bring up bugs and feature requests.  We are just working on cleaning things up and fixing bugs right now.  Hopefully soon we can get a stable 2.0 release.
