### ISSUE TITLE
Owl Carousel 2 - Random elements

### ISSUE THREAD

**Issue by del-mar** [smashingboxes/OwlCarousel2#689]
Hello,
How can I implement this functionality here: http://owlgraphic.com/owlcarousel/demos/randomOrder.html

I want to do random elements of Owl Carousel 2.

Тhank you!

**Comment by del-mar** [comment]
Please help, urgently need to solve this problem.

**Comment by pajasevi** [comment]
Hi, I suppose this should work for you: http://jsfiddle.net/pajasevi/u8w7tm0a/

**Comment by del-mar** [comment]
Super. Thank you very much.

I did it to me like this: http://jsfiddle.net/puo7u39b/ 

Can you look at the code and tell me if this is the best solution? And that can be optimized more?

Тhanks, greetings.

**Comment by pajasevi** [comment]
It looks fine, instead of $("#feedback").owlCarousel({ you can use $owl.owlCarousel({ since $owl was defined before. Glad I could help :)
