### ISSUE TITLE
How do I know the slider is going forward or backward?

### ISSUE THREAD

**Issue by ganlanyuan** [smashingboxes/OwlCarousel2#696]
Hi, could you help this?
How do I know the slider is going forward or backward when the slider is going to change?
owl.on('change.owl.carousel', function(event) {
    next / prev ?
});

Thanks

**Comment by pajasevi** [comment]
Well, I think this one is a bit tricky - I figured, you can get index of now active item using change event, like this
```javascript
$owl.on('change.owl.carousel', function(event) {
    console.log(event.property.value);
})
```
So you can compare indexes of before and after event. Unfortunately, I haven't find clearer solution :disappointed:

**Comment by ganlanyuan** [comment]
Great! That works for me.
Thanks a lot, Pavel Ševčík
