### ISSUE TITLE
URL Hash Navigation - Hash problem in URL

### ISSUE THREAD

**Issue by yucel55** [smashingboxes/OwlCarousel2#698]
Hi,

I love Owl Carousel but I found an issue with the Url Hash Navigation.

when you click on a link the website URL changes to the clicked data name. I tried to solve this with a preventDefault with jQuery but it didnt work.

you can preview the issue here:
http://www.owlcarousel.owlgraphic.com/demos/urlhashnav.html 

when you click on a link this happens: (see #five)
http://www.owlcarousel.owlgraphic.com/demos/urlhashnav.html#five

Hope to find a simple fix.

**Comment by joeyjoejoejr** [comment]
This is intended behavior.  That's why it's cal Url Hash navigation.  What this allows you to do is share a link and have the slider in the right spot.  This is the same way that frameworks like emberjs and angular handle navigation.

**Comment by aviddv1** [comment]
I'm having an issue with the URL hash. Even with the listener option manually set to false, it returns to slide one any time the URL hash changes.

**Comment by aviddv1** [comment]
https://github.com/smashingboxes/OwlCarousel2/pull/369/files

**Comment by faliqaiman** [comment]
I understand that this is Url Hash Navigation function. But is there any chances that we can remove the #five at the end of the URL parameter? The plan is to remain the URL address without additional info at the end of the URL.
