### ISSUE TITLE
Move location of next/prev buttons?

### ISSUE THREAD

**Issue by elacdude** [smashingboxes/OwlCarousel2#699]
Is it possible to move the locations of the next/prev buttons?   I don't like them on the bottom.  I would like to use arrow buttons on the sides.

**Comment by aguilera51284** [comment]
You need to overwrite the .owl-nav class, something like

 .owl-nav {
  font-size: 2em;
  text-align: center;
  -webkit-tap-highlight-color: transparent;
  position: absolute;
  top:40%;
  height:20%;
  width: 100%;
  line-height: 2em;
}

.owl-nav [class*='owl-'] {
  color:  #7f8c8d;
  font-size: 3em;
  display: inline-block;
  cursor: pointer;

}
 .owl-nav [class*='owl-next'] {
  right: -3.5%;
  position:  absolute;

}

**Comment by gaziev** [comment]
OwlCarousel2 issues https://github.com/smashingboxes/OwlCarousel2/issues/663
