### ISSUE TITLE
Is there any chance for owlCaousel to work with jQuery 1.8.2 on chrome !!

### ISSUE THREAD

**Issue by asiyra** [smashingboxes/OwlCarousel2#717]
Hello, 
I have jQuery 1.8.2 on my website and am not able to update the version, is there any chance to work with 1.8.2.

Thanks

**Comment by asiyra** [comment]
Its also not working with jQuery 1.8.3 on chrome.

**Comment by pajasevi** [comment]
Hi @asiyra.

Can you provide detailed information, as described in [README.md](https://github.com/smashingboxes/OwlCarousel2#bug-reports)? Thank you.

**Comment by chippieTV** [comment]
you could try to load in a newer version of jQuery under an alias like this so you can run both versions together
```
<!-- load jQuery 1.1.3 -->
<script type="text/javascript" src="http://example.com/jquery-1.1.3.js"></script>
<script type="text/javascript">
var jQuery_1_1_3 = $.noConflict(true);
</script>

<!-- load jQuery 1.3.2 -->
<script type="text/javascript" src="http://example.com/jquery-1.3.2.js"></script>
<script type="text/javascript">
var jQuery_1_3_2 = $.noConflict(true);
</script>
```
(code from this stackoverflow question)
http://stackoverflow.com/questions/1566595/can-i-use-multiple-versions-of-jquery-on-the-same-page

http://learn.jquery.com/using-jquery-core/avoid-conflicts-other-libraries/
