### ISSUE TITLE
OwlCarousel2 gallery images sometimes do not load completely

### ISSUE THREAD

**Issue by elena18** [smashingboxes/OwlCarousel2#721]
Hi I incorporated Owl Carousel 2 in my page but when loading it sometimes the images do not appear. This happens above all when using a tablet or a smartphone. I should refresh the page 2-3 times to have the images. I tried to reduce the size of the thumbnails (40 kb now) but still it doesn't work

Someone could help me please?
The page is online so you can test it http://elenapoliti.altervista.org/versiliarent/paperette.html

Thank you very much

**Comment by pajasevi** [comment]
Hi, can I ask, why do you have that updateSize() function in there? It is setting 6px height on .owl-wrapper-outer, which is bad.

**Comment by elena18** [comment]
Hi @pajasevi I have added the updateSize function in script as it is required to resize images that have different size, but I never set a 6px height. Where did you find it? I copied the scripts for the carousel in the head section as it appears here

 <script>
	
    $(document).ready(function() {
      $("#owl-demo").owlCarousel({
        autoPlay: 3000,
        items : 3,
		lazyLoad: true,
		navigation: false,
        itemsDesktop : [1199,3],
        itemsDesktopSmall : [979,2],
	    itemsTablet: [768,1],
		itemsTabletSmall: false,
 		itemsMobile : [325,1],
		singleItem : false,		
		itemsScaleUp : false,
        afterUpdate: function () { //serve per il resize delle immagini se hanno dimensioni diverse
            updateSize();
        },
        afterInit:function(){ //serve per il resize delle immagini se hanno dimensioni diverse
            updateSize();
        }
      });
	  //serve per il resize delle immagini se hanno dimensioni diverse
		function updateSize(){
			var minHeight=parseInt($('.owl-item').eq(0).css('height'));
			$('.owl-item').each(function () {
				var thisHeight = parseInt($(this).css('height'));
				minHeight=(minHeight<=thisHeight?minHeight:thisHeight);
			});
			$('.owl-wrapper-outer').css('height',minHeight+'px');
		}	
		   var owl = $("#owl-demo");
			 
			owl.owlCarousel();
			 
			// Custom Navigation Events
			$(".next").click(function(){
			owl.trigger('owl.next');
			})
			$(".prev").click(function(){
			owl.trigger('owl.prev');
	  })
    });
    </script>

**Comment by pajasevi** [comment]
Well, firstly: you are using OwlCarousel, not OwlCarousel2, so this issue really shouldn't be here.

I think I solved your issue [in this fiddle](http://jsfiddle.net/pajasevi/8rxbd5ow/). I used setTimeout() in afterInit callback and it works, maybe you could use smaller number, one second may be too much.

I hope this helps.

**Comment by elena18** [comment]
Thank you very much @pajasevi . It seems to work perfectly now! And yes you are right: I was sure I was using OwlCarousel2 but instead I am using OwlCarousel: sorry for being misleading!

**Comment by pajasevi** [comment]
Glad I could help! :)
