### ISSUE TITLE
Video working with Chinese service Tudou

### ISSUE THREAD

**Issue by richardczeiger** [smashingboxes/OwlCarousel2#728]
I've been having issues getting this to work with the Chinese version of YouTube: Tudou. Any chance of this being integrated?

**Comment by greg5green** [comment]
We're not planning on the time to integrate this as none of us use the service and also can't read Chinese text! If you feel take the time to implement it for yourself, feel free to submit a pull request and we'll see if we can get it merged into the codebase.
