### ISSUE TITLE
Dots Not Showing At All

### ISSUE THREAD

**Issue by imagecrafting** [smashingboxes/OwlCarousel2#734]
No dots for navigation although prev-next are working. Page is located at:
http://dnn.bistromd.com/dev

So using DNN which uses Jquery 1.9.1 and this code at the bottom of the page:

  $('.owl-carousel').owlCarousel({
    loop: false,
    margin: 10,
    navText: ['&#8678; Breakfast', 'Snacks &#8680;'],
    responsiveClass: true,
    responsive: {
      0: {
        items: 1,
        nav: true
      },
      600: {
        items: 2,
        nav: true
      },
      1000: {
        items: 3,
        nav: true
      }
    }

Have tried forcing the 'dots' api call to true and messed with several different settings. This is a stock install of Owl Carousel 2 Beta from the site today.

**Comment by lihao6485** [comment]
Hi @imagecrafting 

I think you are not included the theme css file which is not included in the Owl Carousel 2 beta download, but you can get it from here: https://github.com/smashingboxes/OwlCarousel2/tree/develop/src/css


Regards,
Li Hao

**Comment by imagecrafting** [comment]
That did it, thanks Li Hao!
