### ISSUE TITLE
Lazyload in IE >= 9 - Slider height is misrepresented (too high)

### ISSUE THREAD

**Issue by shaselboeck** [smashingboxes/OwlCarousel2#738]
Hi,

see the demo example:
http://www.owlcarousel.owlgraphic.com/demos/lazyLoad.html

In Firefox and Chrome the dots are displayed just below the slider. In IE there is a distance between the dots and the slider. The dots are also displayed just below the slider, when all images are looped (loaded) once. You can only see it by destroying image 6 and 7, because they will not be loaded correctly from:
http://placehold.it/350x250&text=6
http://placehold.it/350x250&text=7

Whats is the problem viewing it in IE? How can I fix it?

Thanks a lot.

Best regards
Sven.

**Comment by 3rror404** [comment]
I am experiencing the same issue. The height is wrong until all of the slides have loaded. Then the height is corrected
