### ISSUE TITLE
owlcarousel/owl.theme.default.min.css not in download

### ISSUE THREAD

**Issue by johngrabner** [smashingboxes/OwlCarousel2#739]
btw, very cool carousel

**Comment by artivilla99** [comment]
Yeah, do we need this? I can't get my items to stack either. I"m guessing coz I'm missing the owl.theme.default.min.css.

**Comment by cypherjones** [comment]
Anyone figure this out?

**Comment by artivilla99** [comment]
@cypherjones yeah, I don't know why it's not in the download folder but it's in this repo so I'd just download it manually.

**Comment by benwo** [comment]
+1

**Comment by greg5green** [comment]
This has been fixed in the bower install and the [website download](http://smashingboxes.github.io/OwlCarousel2/).

**Comment by moshfeu** [comment]
@greg5green Thanks!
