### ISSUE TITLE
v2 Beta issue with singleItem

### ISSUE THREAD

**Issue by BruceMcKinnon** [smashingboxes/OwlCarousel2#740]
Hi,

I've just been trying out Owl v2 beta and have found the singleItem: true setting stops the carousel from working. I was using:

$("#make-up-courses").owlCarousel({
		navigation : true, // Show next and prev buttons
		slideSpeed : 300,
		paginationSpeed : 400,
		autoPlay: true,
		singleItem:true		
		});

As soon as a switched to v1, without making any config changes, the carousel worked perfectly.

**Comment by robsn** [comment]
It seems that the property "singleItem" is no longer supported with v2.

You should use the property "items" with value 1 for a single slide, or value n for n slides within your slider width.

```javascript
$("#owl-demo").owlCarousel({
    slideSpeed : 300,
    paginationSpeed : 400,
    items: 1,
    dots: false,
});
```
