### ISSUE TITLE
Issue with Jquery 1.8.2 version

### ISSUE THREAD

**Issue by JaiNiranjanM** [smashingboxes/OwlCarousel2#742]
Issue occurs in Chrome broswer while swipe when using Jquery version 1.8.2

The error occurres in 'customEvent' function in jquery.min.js
Uncaught TypeError: boolean is not a functionjquery.min.js 
p.event.triggerjquery.min.js
(anonymous function)jquery.min.js
 p.extend.eachjquery.min.js
 p.fn.p.eachjquery.min.js
 p.fn.extend.trigger
 Owl.trigger
 Owl.animate
 Owl.Pipe.runjquery.min.js
 p.extend.proxy.p.isFunction.f
 Owl.update
 (anonymous function)jquery.min.js
 p.extend.proxy.p.isFunction.f

Please help us to overcome this issue. Thanks in advance.

**Comment by pajasevi** [comment]
Prease read the docmentation. Minumum compatibile jQuery version is 1.8.3 version.

**Comment by JuanHB** [comment]
Tested here, with 1.8.3 I had the same error. Only worked when used the version 1.11.2.

**Comment by greg5green** [comment]
In my testing with 1.8.2 and 1.8.3, everything worked fine with beta 3. [Test case I used](http://codepen.io/anon/pen/BNgzQv)

I'm going to close this issue, but if you are still having problems, please check out https://github.com/smashingboxes/OwlCarousel2/blob/develop/CONTRIBUTING.md#bug-reports and submit a bug report with a codepen or fiddle so we can debug the issue. Thanks.
