### ISSUE TITLE
Missing main css into bower.json (solved)

### ISSUE THREAD

**Issue by clabnet** [smashingboxes/OwlCarousel2#749]
This is my solution to add missing owl.carousel.min.css :+1: 
(please note 2.nd row on main section)
{
  "name": "owl.carousel",
  "version": "2.0.0-beta.2.4",
  "main": [
    "./dist/owl.carousel.min.js",
    "./dist/assets/owl.carousel.min.css"
  ],
  "dependencies": {
    "jquery": ">= 1.7.1"
  },
  "devDependencies": {
    "foundation": "5.2.2"
  }
}

regards

Claudio Barca

**Comment by greg5green** [comment]
This was fixed via 012c20ebb5833602d7055a7cbd12a3c591137ef9
