### ISSUE TITLE
bower.json

### ISSUE THREAD

**Issue by robertbaker** [smashingboxes/OwlCarousel2#753]
Add the default css files to the main array to assist injectors. Add bower.json to 1.3.x

**Comment by leandroruel** [comment]
+1

**Comment by jan-dh** [comment]
Bower installation is somewhat troublesome now, +1

**Comment by greg5green** [comment]
https://github.com/smashingboxes/OwlCarousel2/blob/develop/CONTRIBUTING.md#bug-reports

**Comment by greg5green** [comment]
This was fixed in the beta 3 release.

https://github.com/smashingboxes/OwlCarousel2/blob/2.0.0-beta.3/bower.json
Fixed via 012c20ebb5833602d7055a7cbd12a3c591137ef9
