### ISSUE TITLE
Is this still going?

### ISSUE THREAD

**Issue by lmartins** [smashingboxes/OwlCarousel2#756]
It has been a while since the announcement teaser was posted on the README file but we still haven't got any news and development seems pretty stall. Don't get me wrong, im very thankful to anyone taking over the project but at this point it would be very useful to know if we can expect any progress in the near future.

Thanks.

**Comment by sodbileg** [comment]
+1

**Comment by leandroruel** [comment]
yes, but, by while, they are closing issues here at github and fixing stuffs...wait for more news soon

**Comment by CoryFoy** [comment]
Hi All - I'm the CTO of Smashing Boxes, and my teams are the one that have taken this project over. We have a lot of passion around the project, so yes - we have big plans for Owl Carousel! You'll begin to see a lot more work towards it over the next couple of months, and we also have launched an internal apprenticeship program where our apprentices will be working on open source projects like this.

I know it can be frustrating not seeing immediate progress and plans for something you rely on - but we are working towards improving it and making it better!

**Comment by lmartins** [comment]
Hey @CoryFoy thank you very much for the update, as it confirms it is a good ideia to wait a little more for the project to evolve. Cheers.

**Comment by CoryFoy** [comment]
@lmartins My pleasure! We were very excited to take on the project - there was a lot of back and forth initially getting the repos, organizations and websites transferred over, but we're ready to rock it now! Feel free to let us know if you have any other questions.

**Comment by miniMAC** [comment]
Project dead :(
