### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by hasratyan** [smashingboxes/OwlCarousel2#758]
How to hide right navigation arrow if it is the last item on the carousel. Also for the first item I want to hide left arrow.

Thanks!

**Comment by hasratyan** [comment]
I found the way to disable. Just using CSS I did following.
owl-buttons .disabled{
 visibility:hidden;
}

**Comment by lkdnvc** [comment]
+1 very necessary

**Comment by charmcat** [comment]
+1 extremely necessary!
