### ISSUE TITLE
Invalid Markup Validation when using lazyload. 

### ISSUE THREAD

**Issue by thomeu** [smashingboxes/OwlCarousel2#759]
I get the following error when I try to validate with w3c validator:
Element img is missing required attribute src.

Tried using an empty pixel image but the carousel height doesn't match then. What do you do to pass the validator?

**Comment by woeps** [comment]
A quick search on the web brought up this interesting discussion on stackoverflow: http://stackoverflow.com/questions/5775469/whats-the-valid-way-to-include-an-image-with-no-src

In some tiny tests, two of the mentioned solutions worked for me: `src="#"` or `src="//:0"` - though a flash of "broken image" (by the browser) could appear.

So I guess you'd have a couple of choices:
* use the mentioned markup and build a workaround for the flash of broken image-icons
* add your images dynamically
* aim for "gracefull" degradiation: A possible take on that could be to reference to thumbs using `src` and reference to full-res image using `data-src`. You could even embed the image into separate links and remove them dynamically upon initialisation of the carousel.
This way user with disabled js would be able to navigate through the images in an alternative way, and everyone else, would get the fancy carousel.

I guess, there are a lot of other possible solutions, depending on what you're trying to accomplish. - But still, I hope I could give you some usefull suggestions.

I don't think of this issue as a bug of owl, but still something which could be kept in mind for further development.

**Comment by cortopy** [comment]
I was just working on this precise issue. I don't see it as an owl bug either @woeps 

However, owl lazy-loading doesn't seem to have graceful degradation. The browser loads the thunbs image anyway and then owl requests data-src immediately after. In my timeline both requests appear one after the other for every image. 

While it's not a but, is there a way to make owl download lazy-load images only after the whole document is loaded and there are no more requests needed?
