### ISSUE TITLE
Callback event is empty

### ISSUE THREAD

**Issue by shofer4eto** [smashingboxes/OwlCarousel2#763]
I saw a few issues like this and they have been closed, why if there's no solution found?
Anybody made this work?
Anythings as simple and useful as this should definitely be fixed:
http://www.owlcarousel.owlgraphic.com/docs/api-events.html

function callback(event) {
    ...
}

event is empty though!
Anyone? Thanks!

**Comment by sachbearbeiter** [comment]
+1

**Comment by jakobploens** [comment]
+1000

**Comment by OPM87** [comment]
--> #778

**Comment by greg5green** [comment]
This should be fixed in beta 3 via b01ddd0993f2a706f6f24ff26180dc796d4bc517.

[test case](http://codepen.io/anon/pen/vOqKXR) (event type is dynamically shown in html)
