### ISSUE TITLE
Images moving after carousel initialization.

### ISSUE THREAD

**Issue by shofer4eto** [smashingboxes/OwlCarousel2#764]
I am using a simple image carousel that is initialize on document ready.
When viewing the page though the images get shown one below the other with their initial sizes, then the carousel gets initialized and only after that is finished they line up into a horizontal carousel the way they are supposed to look. Is there anyway that I can fade in the carousel only after it has initialized and this way get rid of that image flickering effect? Thanks! :)

**Comment by KennethAshley** [comment]
Use `$(document).ready()` to execute something when the DOM is loaded and `$(window).load()` to execute something when all other things are loaded, such as images.

**Comment by shofer4eto** [comment]
I am aware of these, was wondering if there's a core solution for this though.
