### ISSUE TITLE
Call Event on trigger

### ISSUE THREAD

**Issue by wtorsi** [smashingboxes/OwlCarousel2#778]
change 
this.settings[handler].apply(this, event);

to this
this.settings[handler].call(this, event);

"apply" requires to use array of arguments

**Comment by OPM87** [comment]
Thanks :)

**Comment by JuanHB** [comment]
+1 to this, please guys add this in the dist lib

**Comment by greg5green** [comment]
This is a limitation of the jQuery API surrounding the [trigger method](http://api.jquery.com/trigger/). We want to be able to pass in multiple parameters when using trigger, so we must use an array. We could use duck typing to help in the instance where there was only one parameter, but that raises some other issues.

**Comment by greg5green** [comment]
Oops, I definitely misinterpreted the question here, so sorry about that. Got confused and assumed this was about `.trigger('event.owl', ['value'])` vs `.trigger('event.owl', 'value').

This fix is in beta 3 and was fixed in b01ddd0993f2a706f6f24ff26180dc796d4bc517
