### ISSUE TITLE
Windows 8.1 slide not working

### ISSUE THREAD

**Issue by GuerrillaCoder** [smashingboxes/OwlCarousel2#782]
Hi,

In Windows 8.1 sometimes (most of the time) the slide doesn't work (occaisionally it does for some weird reason, I have tried in multiple PC's to test). By doesnt work I mean you can't drag it to next slide or click the bullet at the bottom to advance.

I found some old issue where this has been resolved but the links in the issue are broken.  I think from memory it said it was to do with touch events and updating the touch events will fix it.

Can you point me in the right direction for getting beta to work in windows 8.1 please?

Thanks

**Comment by leandroruel** [comment]
what browser you're using?

**Comment by GuerrillaCoder** [comment]
This issue appears in IE and Chrome but works in Firefox.

**Comment by manuelmazzuola** [comment]
Same issue here.
Chromium 42.0.2311.90 (64-bit)

Works on Firefox

**Comment by GuerrillaCoder** [comment]
for reference here is the old issue: https://github.com/smashingboxes/OwlCarousel2/issues/156

**Comment by greg5green** [comment]
Any chance any of you can come up with a test case as mentioned in https://github.com/smashingboxes/OwlCarousel2/blob/develop/CONTRIBUTING.md#bug-reports? I've tried in Win 8.1 with IE 11.0.9600.17416 and Chrome 44.0.2403.157 and I'm not seeing any issues.
