### ISSUE TITLE
Uneven list - preview return to first position

### ISSUE THREAD

**Issue by zeligon** [smashingboxes/OwlCarousel2#787]
When index is not equivalent to preview index + visible items, preview click will return to to first position.

To reproduce, click next twice, and once on preview. Instead of going back once, index goes back all the way..:
http://codepen.io/anon/pen/qEzopE

**Comment by greg5green** [comment]
This is fixed with beta 3.

[test case](http://codepen.io/anon/pen/doBXoz)
