### ISSUE TITLE
autoplay should be autoPlay

### ISSUE THREAD

**Issue by Ev4sIoN** [smashingboxes/OwlCarousel2#789]
I was playing with the carousel earlier and had autoplay in my code (and it is autoplay in the documentation on the options page), but it should be updated to "autoPlay". I did a search and it seems I am not the only one who just kept it all lowercase.

**Comment by squeakcat** [comment]
Did you get autoplay to work?

I tried 3 versions of owl carousel, even copied the code and version from this page:
http://www.owlcarousel.owlgraphic.com/demos/autoplay.html

Cannot get autoplay to work, period.

**Comment by Ev4sIoN** [comment]
@squeakcat Yeah, when I noticed the typo and fixed it, it worked right away. Are you using the right version of owl carousel? I know it might be a dumb question, but when I was fooling around with it I noticed I somehow had the older version (not version 2).

**Comment by greg5green** [comment]
This has been fixed, so closing.
