### ISSUE TITLE
Owl-Stage width increase to huge width px. 

### ISSUE THREAD

**Issue by hauareyou** [smashingboxes/OwlCarousel2#802]
Hello, I am using this for my Liferay website. I have this working perfectly in my Liferay Portlet but one thing. When the window screen size decrease 767px or less I notice Owl-Stage width generate to 23kPX. I can't figure out why? How do I fixed this bug?

**Comment by hauareyou** [comment]
I fixed it. For any future personnel who might run into something similar. Just customized the Media Queries to exact window.

**Comment by dominykaselite** [comment]
Which CSS files did you edit?
