### ISSUE TITLE
OC2 not working with jqeury 1.8.3

### ISSUE THREAD

**Issue by krahamath** [smashingboxes/OwlCarousel2#804]
Why is owlcarousel is not working with jQuery 1.8.3.min ?

**Comment by hauareyou** [comment]
I believe it made for jquery 1.9 or higher. Not 100% sure on that tho.

**Comment by krahamath** [comment]
Then, why they told like:
Dependecies
Get the latest jQuery or Zepto library. Minumum compatibile jQuery version is 1.8.3 version.

**Comment by KennethAshley** [comment]
@krahamath can you show the error you might be getting? Please upgrade to the latest version of OwlCarousel and see if the error still persists.

**Comment by mirrur** [comment]
I have the same problem. It is not working with jQuery 1.8.3.min in Chrome but working in firefox. And i delete line 986(' this.trigger('translate'); ') in file owl.carousel.js, it can work now. But I don't know why. T T

**Comment by greg5green** [comment]
There may have been an issue in beta 2.4, but it works in beta 3 -- [test case](http://codepen.io/anon/pen/PqrNMa)
