### ISSUE TITLE
Chrome blurry text when menu overlays slider

### ISSUE THREAD

**Issue by Emnalyeriar** [smashingboxes/OwlCarousel2#807]
Hey,

I have a dropdown menu that slides down and overlays my slider (fixed position), when this happens text becomes blurry on Chrome.
It seems that it is caused by translate3d on 78 css line, commented it out and it displays fine now.
There is a comment there saying "fix for flashing background" but I don't see any bugs with flashing background after removing this line.

**Comment by KennethAshley** [comment]
@Emnalyeriar can you provide a fiddle or images of the issue?

**Comment by Emnalyeriar** [comment]
Sorry, it was a commercial project I was doing at my job so can't provide an image. I can try to recreate this in a fiddle when I'll have some free time but can't guarantee this bug will occur again

**Comment by KennethAshley** [comment]
@Emnalyeriar A fiddle would work best as i can't really dig into a problem without having more data. Thanks!
