### ISSUE TITLE
Android Browser 4.0

### ISSUE THREAD

**Issue by africanmatt** [smashingboxes/OwlCarousel2#814]
`
.owl-carousel .owl-item img { -webkit-transform-style: preserve-3d; }
`

transform-style on old Android browsers wrecks the rendering of the images completely. Fix by removing the above.

**Comment by iandonovan** [comment]
If this problem is in the latest release of OC, [we welcome pull requests](https://github.com/smashingboxes/OwlCarousel2#contributing) to fix it.
