### ISSUE TITLE
Detecting currently displayed items count

### ISSUE THREAD

**Issue by weronika** [smashingboxes/OwlCarousel2#815]
How can I get currently displayed items count? I initialized carousel with settings showed below:
```
    $carousel.owlCarousel({
        items: 3,
        loop: true,
        center: true,
        mouseDrag: false,
        autoplay: true,
        autoplayTimeout: 8000,
        autoplayHoverPause: true,
        responsive: {
            0: {
                items: 1
            },
            600: {
                items: 3
            }
        }
    });
```

How can I detect if currently carousel shows 3 items or only 1 item?

**Comment by aleroy** [comment]
var visibleItems = $('.owl-item.active').length;

If you have more than one carousel:

    var visibleItemsInA = $('#owl_a').find('.owl-item.active').length;
    var visibleItemsInB = $('#owl_b').find('.owl-item.active').length;
