### ISSUE TITLE
Incorrect slides position due to pixels with decimals

### ISSUE THREAD

**Issue by RedskyThirty** [smashingboxes/OwlCarousel2#817]
Hello,

I've added "Math.round()" to the items width calculation because I obtained an increasing white space after clicking on the "next" control (owl-next).

```
var rtl = (this.settings.rtl ? 1 : -1),
				width = Math.round(this.width() / this.settings.items).toFixed(3),
				coordinate = 0, merge, i, n;
``` 
and
```
var i, n, width = Math.round(this.width() / this.settings.items).toFixed(3), css = { ... }
```
This will prevent some css values like "width:100.25px;".

**Comment by iandonovan** [comment]
Please [make a pull request](https://github.com/smashingboxes/OwlCarousel2#contributing) if you'd like this feature added to the project.
