### ISSUE TITLE
Dynamic carousel content.

### ISSUE THREAD

**Issue by Jiig** [smashingboxes/OwlCarousel2#819]
I need to load all carousel content dynamically for a single page web app. Ive tried using:
    $('#owl-demo').owlCarousel('add', a).owlCarousel('refresh');
to load the items individually, and remove to remove them.

When I call add the content doesn't get added to the dom according to firebug, but im not getting any js errors in the console.

Is there an error callback that im missing? Or does this not work the way im thinking it should?

**Comment by aleroy** [comment]
Try this:

    $('#owl-demo').trigger( 'add.owl.carousel', [$('<div class="owl-item">foo</div>')] )
                  .trigger( 'refresh.owl.carousel' );
