### ISSUE TITLE
Fade to white

### ISSUE THREAD

**Issue by thankyouverymuch** [smashingboxes/OwlCarousel2#821]
Hi all!
I set up OwlCarousel2 today and it works only on firefox.
On Chrome, occasionally the image fade to white (background color).
I have 4 pictures and first 2 images fade fine but after that they just change the image. (no fades)
On IE, it doesn't work at all.
Could anyone help me to solve this?
Thanks!

I checked several browsers and they all behave differently.
Firefox36     ----  worked fine!
Chrome42   ----  occasional fade to white
IE 11 ---  doesn't work at all (not even an empty space)

**Comment by nsams** [comment]
Please create a testcase like described here: https://github.com/smashingboxes/OwlCarousel2#bug-reports

**Comment by thankyouverymuch** [comment]
OK, I'll try to create one.

**Comment by gideonheilbron** [comment]
Can you try the fix I described here: https://github.com/smashingboxes/OwlCarousel2/issues/772 I think it might be related.

**Comment by thankyouverymuch** [comment]
Thanks gideonheilbron,

All pictures start showing but no fading now.
Strange thing is on different page in the same website where I set width works fine...
On Firefox, it works perfectly on every page.
On IE, it still doesn't work at all.
It doesn't even show the empty space...

(I still couldn't create a testcase.)

**Comment by thankyouverymuch** [comment]
I solved IE part.
It really silly of me.
There was an old "meta" set to emulate IE7...
I deleted the line.
However, Owl still doesn't fade.

Now the problem is only about fading on Chrome and IE11.

**Comment by gideonheilbron** [comment]
Hmm.. Could you create a codepen or something with an example?
