### ISSUE TITLE
Incorrect slide loaded with URLhash if loop is true

### ISSUE THREAD

**Issue by isabisa** [smashingboxes/OwlCarousel2#822]
I noticed that if loop is true, the slide 2 slides down from where the correct target slide is gets loaded.

For example:

```javascript
$('.owl-carousel').owlCarousel({
  items: 1,
  loop: true,
  URLhashListener:true,
  startPosition: 'URLHash'
});
```

```html
<ul>
  <li><a href="#one">1</a></li>
  <li><a href="#two">2</a></li>
  <li><a href="#three">3></a></li>
  <li><a href="#four">4</a></li>
  <li><a href="#five">5</a></li>
</ul>

<div class="owl-carousel">
  <div data-hash="one">
    Slide 1
  </div>
  <div data-hash="two">
    Slide 2
  </div>
  <div data-hash="three">
    Slide 3
  </div>
  <div data-hash="four">
    Slide 4
  </div>
  <div data-hash="five">
    Slide 5
  </div>
</div>
```

If you click on the link for 1, the hash will change to #one, but Slide 3 will load. If you click on the link for slide 2, the hash will change to #two, but Slide 4 will load. Etc...

But if you change loop to false, it behaves as expected.

**Comment by simonbbrown** [comment]
I spent some time looking into this - I was able to fix it by updating to this:
https://github.com/simonbbrown/OwlCarousel2/commit/7e90b135b31f743bffcf9253cda1f4211b71675b

**Comment by danielellm** [comment]
for me is not working with the update
still the same problem

<div class="section slide_content" >
      <div class="container container_slide" style="padding:0 55px;width:100%;"><div class="owl_slider" class="owl-carousel"><div class="col-md-12 item" style="width: 100%;height: auto;margin:0 auto;text-align: center;" data-hash="asop1" >
<img src="index.php?rex_media_type=full&rex_media_file=asop01.jpg" alt="" class="img-responsive" style="display: inline;">
</div><div class="col-md-12 item" style="width: 100%;height: auto;margin:0 auto;text-align: center;" data-hash="asop2" >
<img src="index.php?rex_media_type=full&rex_media_file=asop02.jpg" alt="" class="img-responsive" style="display: inline;">
</div><div class="col-md-12 item" style="width: 100%;height: auto;margin:0 auto;text-align: center;" data-hash="asop3" >
<img src="index.php?rex_media_type=full&rex_media_file=asop03.jpg" alt="" class="img-responsive" style="display: inline;">
</div><div class="col-md-12 item" style="width: 100%;height: auto;margin:0 auto;text-align: center;" data-hash="asop4" >
<img src="index.php?rex_media_type=full&rex_media_file=asop04.jpg" alt="" class="img-responsive" style="display: inline;">
</div><div class="col-md-12 item" style="width: 100%;height: auto;margin:0 auto;text-align: center;" data-hash="asop5" >
<img src="index.php?rex_media_type=full&rex_media_file=asop05.jpg" alt="" class="img-responsive" style="display: inline;">
</div><div class="col-md-12 item" style="width: 100%;height: auto;margin:0 auto;text-align: center;" data-hash="asop6" >
<img src="index.php?rex_media_type=full&rex_media_file=asop06.jpg" alt="" class="img-responsive" style="display: inline;">
</div><div class="col-md-12 item" style="width: 100%;height: auto;margin:0 auto;text-align: center;" data-hash="asop7" >
<img src="index.php?rex_media_type=full&rex_media_file=asop07.jpg" alt="" class="img-responsive" style="display: inline;">
</div>
</div>
</div>




var owl = $('.owl_slider'),
status = $('#owl_status');

owl.on('initialized.owl.carousel change.owl.carousel changed.owl.carousel', function(e) {
if (!e.namespace || e.type != 'initialized' && e.property.name != 'position') return
        var current = e.relatedTarget.current() +1;
        var items = e.item.count;

$('.owlItems').text(items);
$('.currentItem').text(current);
        
    }),

owl.owlCarousel({
center: true,
singleItem:true,
items:1,
loop:true,
itemsScaleUp:true,
URLhashListener:true,
startPosition: 'URLHash',

});


http://57438451.swh.strato-hosting.eu/cms/beauty/
