### ISSUE TITLE
Parameter undefined in callbacks

### ISSUE THREAD

**Issue by nitsch** [smashingboxes/OwlCarousel2#824]
Testing with the exact same code presented in the [callback example](http://www.owlcarousel.owlgraphic.com/docs/api-events.html#callbacks), I am unable to access the `event` argument that is passed into the handler. It is always `undefined`. Everything else is working.

I am using the 2.0.0-beta.2.4 downloaded from http://www.owlcarousel.owlgraphic.com.

**Comment by greg5green** [comment]
Looks like a duplicate of this issue: #526.
