### ISSUE TITLE
Issue with bootstrap tabs showing only one item 

### ISSUE THREAD

**Issue by SantiPlanet** [smashingboxes/OwlCarousel2#825]
Dear all,

I've been testing Owl2 and it's great but, although in issue #239 it was explained a solution for Owl2 when included in tabs, that solution doesn't solve this: the number of items to show is ignored. Do you have any solution for this?

Check this jsfiddle: http://jsfiddle.net/Epmwx/ . Althought it seems to work fine, if you define: "items: 1", this parameter is ignored.

Thank you very much!

**Comment by aleroy** [comment]
Forget about the items option ... use:

    $('.owlCarousel').owlCarousel(
    {
        //...
        responsive:
        {
            0:    { items:1 },
            600:  { items:1 },
            1000: { items:1 }
        },
        //...
    });

**Comment by SantiPlanet** [comment]
Thank you, aleroy. But I've tested it and it doesn't seem to work: http://jsfiddle.net/e9b7fh70/4/

As you can see, in first tab I try with 2 items and in the second one with 1 item. But it has no effect.

**Comment by aleroy** [comment]
You need to add a handler to each of your bootstrap tabs that trigger the owl inside the tabpanel to update.

**Comment by SantiPlanet** [comment]
Thank you, aleroy. I trust you but I must say that I'm not able to get it work... I'll keep trying!

**Comment by iandonovan** [comment]
Thanks for helping out, @aleroy

**Comment by mohsincynexis** [comment]
@aleroy  your solutions is not working for me. 
Can you let me know what am doing wrong.` $("a[data-toggle='tab']").on('shown.bs.tab', function(e) {

        $('.slide-carousel').owlCarousel({
            margin: 10,
            nav: false,
            loop: false,
            dots: true,
            responsiveClass: true,
            responsive:
            {
                0:    { items:1 },
                600:  { items:1 },
                1000: { items:1 }
            }
        });

    });`
