### ISSUE TITLE
Navigation Buttons inside the carousel

### ISSUE THREAD

**Issue by omrteko** [smashingboxes/OwlCarousel2#827]
I was searching about a way to make the navigation buttons inside the slides, the right arrow on the right position and the left on the left, but I didn't found a solution either in the documentation and out-side the documentation so I decided posting here!

**Comment by nvaldes** [comment]
Also saw this gap in functionality, so I disabled the built-in nav buttons and rolled my own.  Here's the relevant code:

    <style>
      #jm-Section-CARU{
        position: relative;
        margin: 0;
        text-align: center;
      }
      .next, .prev {
        display: none;
        position: absolute;
        top: calc(50% - 18px);
        z-index: 3;
        height: 36px;
        width: 36px;
        background: rgba(255, 255, 255, 0.74);
      }
      .next:hover, .prev:hover {
        background: rgba(255, 255, 255, 0.94);
      }
      .next {
        right: 0;
      }
      .prev {
        left: 0;
      }
      .prev a{
        display: inherit;
        -ms-transform: rotate(270deg);
        -webkit-transform: rotate(270deg);
        transform: rotate(270deg);
        background: url("/resources/images/layout/chevron.png") center no-repeat;
        width: 32px;
        height: 34px;
      }
      .next a {
        display: inherit;
        -ms-transform: rotate(90deg);
        -webkit-transform: rotate(90deg);
        transform: rotate(90deg);
        background: url("/resources/images/layout/chevron.png") center no-repeat;
        width: 32px;
        height: 40px;
        float: right;
      }
      .owl-theme .owl-controls {
        position: absolute;
        margin: 0;
        width: 100%;
        bottom: -9%;
      }
      .owl-theme .owl-dots .owl-dot span {
        background-color: rgba(170, 170, 170, 0.88);
        height: 8px;
        width: 8px;
      }
      .owl-theme .owl-dots .owl-dot.active span, .owl-theme .owl-dots .owl-dot.active:hover span {
        background-color: rgba(0, 0, 0, 0.88);
      }
      .owl-theme .owl-dots .owl-dot:hover span {
        background-color: rgba(51, 51, 51, 0.88);
      }
      .owl-item{
        z-index:1; /* Fix for OwlCarousel2 Issue #772 (loop flicker) */
      }
    </style>


    
    <section id="jm-Section-CARU">
      
      <nav class="next" style="display: none;">
        <a class="customNextBtn" href="#">&nbsp;</a>
      </nav>
      <nav class="prev" style="display: none;">
        <a class="customPrevBtn" href="#">&nbsp;</a>
      </nav>
      
      <div class="owl-carousel" id="owl-example">
        
      </div>
    </section>
    


    <script>
      function showNav(e){
        if ($(".next").css("float") == "right") {
          $(".next").fadeIn();
          $(".prev").fadeIn();
        }
      }
      function hideNav(e){
        $(".next").fadeOut();
        $(".prev").fadeOut();
      }
      $("#jm-Section-CARU").hover(showNav, hideNav);
      $('.customNextBtn').click(function(e) {
        e.preventDefault();
        $(".owl-carousel").trigger('next.owl.carousel');
      });
      $('.customPrevBtn').click(function(e) {
        e.preventDefault();
        $(".owl-carousel").trigger('prev.owl.carousel');
      });
      $(document).ready(function($) {
        $(".owl-carousel").owlCarousel({
          //CONFIG OBJECT
        });
    </script>


And this is what our carousel looks like:
![image](https://cloud.githubusercontent.com/assets/4739867/7566964/026f86fc-f7c8-11e4-9446-35d0a943a432.png)


Hope it helps!!

**Comment by gideonheilbron** [comment]
I'm sorry, but this is a really cumbersome solution for such a simple problem. Why do you want the next/prev buttons inside the slides? If you want them visually inside the slides you only have to add:

.owl-carousel {
position: relative;
}
.owl-prev,
.owl-next {
position: absolute;
top: 50%;
margin-top: -10px; // Half of the prev/next buttons height here in negatives to center them perfectly
}
.owl-prev {
left: 0;
}
.owl-next {
right: 0;
}

**Comment by nvaldes** [comment]
Iirc (this was about a year ago), there was a specific reason that we couldn't do it that way.  Don't remember the details, but I do know that the custom controls let us put analytics tags on the click callback just recently.  I stripped those out before pasting in the js.

**Comment by hussainsocial** [comment]
nav: true,
        navText: ["<img src='/assets/images/read-more-icon.png'>","<img src='/assets/images/read-more-icon.png'>"],

**Comment by ursbraem** [comment]
Sorry for posting to this closed issue... @gideonheilbron @nvaldes could it be that the problem with the simple solution is that the 50% are calculated including the caption? At least, that's what I get. The buttons are right in the center of the stage (including the caption) – but not of the image.

**Comment by edubasabe** [comment]
Hi, this worked for me, to align vertically the prev & next buttons and put on the sides and align the dot navigation at the bottom of the carousel I did this:

SCSS:
.owl-carousel {
  position: relative;
  .item {
    position: relative;

    img {
      position: relative;
    }

    p {
      position: absolute;
      font-size: 1.8rem;
      top: 50%;
      left: 50%;
      transform: translate(-50%,-50%);
    }
  }

    .owl-controls {
      position: relative;;
      top: 0;
      left: 0;
      transform: translate(0%,-100%);
      width: 100%;
    }

    .owl-nav {
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%,-50%);
      width: 100%;

      .owl-prev {
        float: left;
      }
      .owl-next {
        float: right;
      }
    }

    .owl-dots {
      position: absolute;
      bottom: 0;
      left: 50%;
      transform: translateX(-50%);
    }
}

JS:
var winHeight = $(window).height();
$(document).on('ready', function() {
  $('.owl-controls').css({ 'height': winHeight});
});

**Comment by gideonheilbron** [comment]
No need to use javascript to set a height @edubasabe ... Just use css:

```
.owl-controls {
  height: 100vh;
}
```

**Comment by edubasabe** [comment]
Thank you @gideonheilbron

**Comment by ursbraem** [comment]
Thanks to all of you!

**Comment by MWDavidH** [comment]
You can move `owl-nav` into `owl-stage-outer` on initilization and customize it with css after 

```js
$('.owl-carousel').owlCarousel({
  callbacks: true,
  onInitialized: moveNav
});
function moveNav() {
  $('#main-slider .owl-nav').appendTo('.owl-stage-outer');
}
```

**Comment by hemanthsp** [comment]
please some one upload code to this website http://jsfiddle.net

**Comment by wuwu2000** [comment]
hey hmanthsp, I did a jsfiddle just for you.
https://jsfiddle.net/1har7hum/

But I think the previous comments showing a solution just perfect
