### ISSUE TITLE
(Bug?) Two dots at once

### ISSUE THREAD

**Issue by xxRockOnxx** [smashingboxes/OwlCarousel2#830]
So i have a stock owl carousel i downloaded from the main site, i looked at the issues here and found out that i need to download the theme.default to have those dots. I downloaded it and I have dots now, the problem is I have two dots active on my 3 dots slider and 1 dot active on a 2 dot slider but it's not moving.

**Comment by aleroy** [comment]
Can you reproduce it in a JSFiddle?

**Comment by xxRockOnxx** [comment]
Sorry for the late reply, got busy.

it literally has two active dots at once. Here's my script

$('#headerCarousel').owlCarousel({
loop:true,
		items:1,
		autoplay:false,
	});

**Comment by iandonovan** [comment]
Please provide a fiddle to reproduce this issue.
