### ISSUE TITLE
Great work in the dev branch

### ISSUE THREAD

**Issue by aleroy** [smashingboxes/OwlCarousel2#831]
I keep trying to start new issues ... only to find them implemented in the dev branch (or one of the forks). I especially like the new jquery plugin implementation. That should go a long ways in helping stabilize ...everything.

Hope the next release is coming soon ... I'll try to help with that last 10% [to the beta 3 milestone] if I find a little free time.

**Comment by Marc-pi** [comment]
@aleroy 
hum, what forks?


@greg5green @CoryFoy 
is there a plan to merge the actual PRs or clean up the list, so it looks cleaner and we can help at testing?
is a new beta in the pipe?
it's extremely difficult to follow things here : some fix in the PR, some in the issues...
please let us know

**Comment by aleroy** [comment]
@witrin's fork ... specifically his prefetch addition to the lazyOwl plugin

**Comment by Marc-pi** [comment]
yep, his latest PR and contribution to this project. i thought you were talking about another fork.
i hope we can get some news about this project and its updates...

**Comment by greg5green** [comment]
Sorry guys, time has been sparse! Right now, we're currently working on making it easy for us to build the site, publish the site, publish the plugin as automated as we'd like, etc. Getting a published version of everything that is in the `develop` branch out to bower/npm/the website is our first priority, then after that I think the goal is to release another beta with the current PRs merged in once we test them/take a look at them (and hopefully add tests as we can/if we need to!).

**Comment by greg5green** [comment]
btw, we much appreciate the work and sorting out of issues that has been done :)
