### ISSUE TITLE
JSFiddle linked in README.md doesn't work

### ISSUE THREAD

**Issue by aleroy** [smashingboxes/OwlCarousel2#832]
The [JSFiddle](http://jsfiddle.net/eqbL6vLb/) linked in the README.md gives the following error:

`Uncaught TypeError: $(...).find(...).andSelf is not a function        owl.hash.js:49`

**Comment by iandonovan** [comment]
Good catch!

**Comment by greg5green** [comment]
Fixed in 77a4fcefd442e2047d2dd6195d5452dc4d2fde44
