### ISSUE TITLE
Confusion regarding documentation: inconsistency in the documentation?

### ISSUE THREAD

**Issue by icyflame** [smashingboxes/OwlCarousel2#840]
These two pages mention the event to be triggered in case I want to stop the autoplay of a carousel:

1. http://www.owlcarousel.owlgraphic.com/docs/api-events.html

    mentions the event to be `stop.owl.autoplay`

2. https://github.com/smashingboxes/OwlCarousel2/issues/234

    This issue mentions that the event is `autoplay.stop.owl`

Are there two versions out there?

And also, is the issue #234 the one that is currently on this repository? Which branch are the changes there deployed on?

**Comment by icyflame** [comment]
Another inconsistency is found here:

In the owlCarousel lazy load functionality, I found two pages:

1. http://owlgraphic.com/owlcarousel/demos/lazyLoad.html

    Says that the class should be `class="lazyOwl"`

2. http://www.owlcarousel.owlgraphic.com/demos/lazyLoad.html

    Says that the class should be `class="owl-lazy"`

**Comment by jazibobs** [comment]
Hi icyflame I believe the confusion is coming from you accessing the documentation for 2 versions of this plugin concurrently.

E.g.: 

http://owlgraphic.com/owlcarousel/demos/lazyLoad.html is for OwlCarousel v1
http://www.owlcarousel.owlgraphic.com/demos/lazyLoad.html is for OwlCarousel v2

Make sure you're looking at the correct documentation for the version of OwlCarousel you're developing with.

**Comment by icyflame** [comment]
@jazibobs 
I was using v1, and trying to trigger the event, which was given in the docs of v2. Thanks for the help!
