### ISSUE TITLE
Build the develop branch and put it up on the repository?

### ISSUE THREAD

**Issue by icyflame** [smashingboxes/OwlCarousel2#841]
To build the newest version, the following steps have to followed:

1. install npm
2. install bower
3. run `npm install` and `bower install`
4. run `grunt dist`

Would you consider distributing a built version of the plugin on the repo itself?

**Comment by greg5green** [comment]
We're still [unfortunately] in a bit of a transition stage from taking over the repo, but in the next few weeks, you [hopefully] should be able to find a built version on the plugin in the `gh-pages` branch (and also on bower and npm and stuff)

**Comment by icyflame** [comment]
Thanks a lot, Greg!
