### ISSUE TITLE
Uncaught TypeError: Cannot read property 'index' of undefined

### ISSUE THREAD

**Issue by envil** [smashingboxes/OwlCarousel2#845]
I'm developing a website using angularjs and OC2.
There is a problem when I have my home page with a carousel running, then I switch to another view (by angular, basically angular change the DOM without reload page). Now the carousel DOM part is no longer available on the page.
Now there was an error thrown periodically on the console (note that VM17228 is the carousel.js):
![capture](https://cloud.githubusercontent.com/assets/775364/7787310/55a11d6a-022f-11e5-8298-507f893cbd96.png)

When I set a breakpoint at line 1413 and type this following line:
this.dom.$items.eq(position).data('owl-item')
>undefined

**Comment by envil** [comment]
Updated to the beta 4 and the problem gone.

**Comment by vdv73rus** [comment]
I had the same problem.
@envil Do you mean 2.0.0 - beta 2.4 or what?

**Comment by envil** [comment]
@vdv73rus I download the latest one on the homepage. Probably 2.0.0 beta 4.

**Comment by Gibigbig** [comment]
Can someone update the package? This bug persists and adding the new Owl Carousel 2.4 directly doesnt work.
