### ISSUE TITLE
Documentation for Autoplay is incorrect

### ISSUE THREAD

**Issue by alistairstead3408** [smashingboxes/OwlCarousel2#855]
http://www.owlcarousel.owlgraphic.com/demos/autoplay.html

uses ```owl.trigger('autoplay.play.owl',[1000])``

the api is actually ```owl.trigger('play.owl.autoplay',[1000])``

**Comment by iandonovan** [comment]
Thanks for alerting us! We'll be sure to make this fix when we roll out the new documentation/demo site.

**Comment by greg5green** [comment]
Dupe of #306, fixed in f9ae105bd2c73eafbae06a23cbae4b102e8eb413
