### ISSUE TITLE
With Center option specified, Carousel does not re-center items when scroll bar appears

### ISSUE THREAD

**Issue by Sinistralis** [smashingboxes/OwlCarousel2#857]
Resizing the browser manually causes the carousel to detect the scrollbar and fix itself, however this should be done automatically.

**Comment by iandonovan** [comment]
Please try this again with the [newest version of Owl Carousel](http://smashingboxes.github.io/download/owl.carousel.2.0.0-beta.3.zip). If the issue persists, please reopen the issue to be more in line with our [bug reports guide](https://github.com/smashingboxes/OwlCarousel2/#bug-reports).
