### ISSUE TITLE
newbie needs drastic help - thanks!

### ISSUE THREAD

**Issue by sharklaserx2** [smashingboxes/OwlCarousel2#862]
I am having the most hardest time trying to figure out how to get Owl Carousel working.  I am trying to figure out Owl Carousel 2.  I tired the first version and I got no where, so I figured I would attempt the beta version because that is just how I roll!  I figured I really cannot mess anything up. aha.

Also, do I need Zepto.js?  It indicates it is a dependency.  How would I include that in with all the files?  How would I refer it on my page?  Would I include it in the .info file?

I have tried this for a full day and still no luck.  I do not understand why it is not working. When I followed the instructions online I just get the section blank.. nothing.  I am not sure if anyone could basically help me out (hand holding) but I would appreciate it if anyone could.

This is the file structure I have as of now: (where all the files are kept)
sites/all/libraries/owlcarousel

within this folder (owlcarousel) I have:
=js folder
-ajax-loader.gif
-owl.carousel.css
-owl.carousel.min.css
-owl.theme.default.css
-owl.theme.default.min.css
-owl.theme.green.css
-owl.theme.green.min.css
-owl.video.play.png

Within the js folder I have:
-owl.carousel.js
-owl.carousel.min.js

Okay, so then we go outside the libraries folder and back into the actual page I want to focus on (page--front.tpl.php). I did shorten the link.  I checked the link and it does point to the text file of all files (css and js).

this is what I have at the top of the page....

link rel="stylesheet" href="http://../owl.carousel.min.css">
link rel="stylesheet" href="http://../owl.theme.default.min.css">

I had to remove the < in front of link because it would not display!

this is what I have in the middle of the page:

<?php if ($page['slideshow']) : ?>
div class="owl-carousel">
  div> Your Content </div>
  div > Your Content </div>
  div > Your Content </div>
  div > Your Content </div>
  div > Your Content </div>
  div > Your Content </div>
  div > Your Content </div>
/div>
<script>$(document).ready(function(){
  $(".owl-carousel").owlCarousel();
});</script>

<script src="http://../js/jquery.min.js"></script>
<script src="http://../js/owl.carousel.min.js"></script>

I am so new to Drupal that I am just at a holding point.  I tried my best with everything but I just feel as if I need that extra push to get me right back on track.

I would like to know if there is a way to create a slideshow with the progress bar and at the same time have text? So half the screen with have the image and right next to it would be information about the event.

Thanks so much.

**Comment by leandroruel** [comment]
some styles you need set for yourself, but your markup seems wrong.

```html
<div class="carousel" id="mycarousel">
<div class="item"><img src="dir/image1.jpg"></div>
<div class="item"><img src="dir/image2.jpg"></div>
<div class="item"><img src="dir/image3.jpg"></div>
</div>
```

and the js:

```js
$('#mycarousel').owlCarousel({
items: 1,
loop: true,
nav: false,
dots: true,
autoplay: true,
autoplayTimeout: 2000,
animateIn: "fadeIn",
animateOut: "fadeOut"
});
```

to the fade in and fade out effects work you need include the [Animate.css](https://daneden.github.io/animate.css/) together with owlcarousel css.

the styles that you need set for yourself is for the dots and nav arrows. to do it, just search for nav and dots class inspecting the code with dev tools, or just copy from owl carousel site.
