### ISSUE TITLE
Center demo "broken"

### ISSUE THREAD

**Issue by MeMyselfI** [smashingboxes/OwlCarousel2#864]
Hi.

In the "center" demo the center card doesn't seem to have a special CSS effect on it so it doesn't show the idea behind it.

As the "new pull request button" seems to be broken now: I would like to see that the "home" slide is set on-the-fly while dragging - not at the end of the dragging (perhaps using an option "home-change-on-dragging" o.s.l.t.).

**Comment by iandonovan** [comment]
Hello!

I'm not entirely sure what this issue is about. Please read our [bug reports guide](https://github.com/smashingboxes/OwlCarousel2/#bug-reports) if it's a bug, and read the [contributing guide](https://github.com/smashingboxes/OwlCarousel2/#contributing) for how to create pull requests.
