### ISSUE TITLE
How to add a title for videos?

### ISSUE THREAD

**Issue by praveenmm** [smashingboxes/OwlCarousel2#865]
can i show a title/caption on every videos in slider?

**Comment by leandroruel** [comment]
your carousel have only videos or images too?

**Comment by KennethAshley** [comment]
You can simply add a title to each slide by adding markup inside the individual slide parent container and styling it as desired.

**Comment by praveenmm** [comment]
thankyou

On Fri, Jun 19, 2015 at 11:31 PM, Kenneth Ashley <notifications@github.com>
wrote:

> Closed #865 <https://github.com/smashingboxes/OwlCarousel2/issues/865>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smashingboxes/OwlCarousel2/issues/865#event-335481269>
> .
>



-- 
*Thanks and regards*

*  Praveen M M*
* +919633322348*

**Comment by praveenmm** [comment]
it worked

On Sat, Jun 20, 2015 at 9:24 AM, praveen ..m <praveenmm93@gmail.com> wrote:

> thankyou
>
> On Fri, Jun 19, 2015 at 11:31 PM, Kenneth Ashley <notifications@github.com
> > wrote:
>
>> Closed #865 <https://github.com/smashingboxes/OwlCarousel2/issues/865>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/smashingboxes/OwlCarousel2/issues/865#event-335481269>
>> .
>>
>
>
>
> --
> *Thanks and regards*
>
> *  Praveen M M*
> * +919633322348*
>



-- 
*Thanks and regards*

*  Praveen M M*
* +919633322348*
