### ISSUE TITLE
Windows 8.1 + touchscreen notebook + Chrome problems

### ISSUE THREAD

**Issue by mgntrn** [smashingboxes/OwlCarousel2#867]
Hi,

I've found a weird problem. When using the plug-in on a touch screen notebook (Sony Vaio Pro 13) running Windows 8.1, I can't click the prev/next buttons to control the slider. It's also impossible to move the carousel by click-dragging. The strange thing is this only happens in Chrome, not in FireFox. When I use the touch screen I can control the slider, but it seems impossible to control the touchscreen by mouse.

I've tested on non-touch notebooks, no problem there. It seems other plug-ins also have this problem: https://github.com/dbushell/Nestable/issues/92

mgntrn

**Comment by iandonovan** [comment]
Please try again with the [newest version of Owl Carousel](http://smashingboxes.github.io/download/owl.carousel.2.0.0-beta.3.zip)

If the issue persists, please re-open this and we'll work towards getting a pull request in along [these lines](https://github.com/dbushell/Nestable/issues/92#issuecomment-44962944).
