### ISSUE TITLE
Lots of issue with Chrome

### ISSUE THREAD

**Issue by xmanflash** [smashingboxes/OwlCarousel2#875]
I have 3 images being loaded of various width from about 10 images in total.

The works well in Firefox, but no Chrome, the .js seems to fire before the images are loaded, causing width issues (the images are random widths but the same height)

Resizing fixes it (as long as the images are loaded).

**Comment by xmanflash** [comment]
So I delayed loading owl-carousel() until the images were all loaded (I added a "loading" icon) - and all seems well now..  You may need an option to do this in the system..

**Comment by raknjak** [comment]
I can confirm this issue:
width is calculated incorrectly, then after resize or f12 it works.

BEFORE
![owl-before](https://cloud.githubusercontent.com/assets/1079140/8253939/a3475d3a-1694-11e5-9a89-a51429b01a1f.png)

AFTER
![owl-after](https://cloud.githubusercontent.com/assets/1079140/8253938/a34551c0-1694-11e5-9b9e-1ff9579a240e.png)

Workaround is putting call in $(window).load(function(){...}
cheers!

**Comment by xmanflash** [comment]
Thanks raknjak, yes - I used  $(window).load(function(){...} as well  :)

**Comment by iandonovan** [comment]
Glad you found a workaround!

Please try this issue in the newest version of OC, which was released today. If it persists, we'd welcome a PR to lock the issue away for good.

**Comment by raknjak** [comment]
Hello and thanks for your answer
I just tried with the latest version and at least to me it doesn't seem to be fixed.
someone needs to confirm however to be sure.
cheers!
