### ISSUE TITLE
Clonend elements doesn't Sync

### ISSUE THREAD

**Issue by ceehaupt** [smashingboxes/OwlCarousel2#876]
Hey,

I was synchronizing two carousels and made the one I use as navigation for the other center:true and loop:true. If I'm setting the other carousel on loop:true too, it's broken and fading all the time between different slides. If I do not set the loop on true for the other one the navigation works, as long as I come to an cloned element.

**Comment by iandonovan** [comment]
Please read our [bug reports guide](https://github.com/smashingboxes/OwlCarousel2#bug-reports) and reopen the issue with some more information if it persists on the latest version of OC.

Thank you!
