### ISSUE TITLE
lazyload and firefox

### ISSUE THREAD

**Issue by Codeia** [smashingboxes/OwlCarousel2#878]
Hi. Just a small bug report.
There's a strange problem with lazyLoad and Firefox:
Sometimes the images wont be faded in..
This doesn't happen on chrome.

**Comment by iandonovan** [comment]
Please try this out in the newest version of Owl Carousel.

If the issue persists, please read our [Bug Report Guide](https://github.com/smashingboxes/OwlCarousel2#bug-reports) and re-open the issue with additional information.
