### ISSUE TITLE
Not Chaning the Dots

### ISSUE THREAD

**Issue by himadriganguly** [smashingboxes/OwlCarousel2#879]
In the responsive demo the owl carousel dots are not changing. Mainly the last dot when active is not changed. You can checkout the demo at http://owlcarousel.owlgraphic.com/demos/responsive.html.

**Comment by alo** [comment]
+1
It's only the last dot. Only if you don't change the whole group of photos.

**Comment by iandonovan** [comment]
Hi!

This issue is fixed -- or I suppose, to be more accurate, replaced -- in the new version of our documentation website. That's coming Soon (TM).
