### ISSUE TITLE
Link broken in Classes page in documentation

### ISSUE THREAD

**Issue by antoniomangiacapra** [smashingboxes/OwlCarousel2#880]
Hello,

I report that in page http://www.owlcarousel.owlgraphic.com/docs/api-classes.html, link "callbacks" in the end of page is broken.

**Comment by iandonovan** [comment]
This updated in our newest documentation and will be updated soon. [Here is the commit](https://github.com/smashingboxes/OwlCarousel2/commit/a1fc23eef01d75ea35ca206474af52e2c6b31317).
