### ISSUE TITLE
Error when only one image is in carousel 

### ISSUE THREAD

**Issue by yratof** [smashingboxes/OwlCarousel2#881]
Getting this error when `$('.owl-carousel').owlCarousel({ items: 1 }` is set

`undefined: (evaluating 'd[c[c.length-1]].clone')`

Seems to be related to line:135

    e > 0 ? (this.$stage.children().eq(d.length + c.length - 1).remove(), c.pop(),
    this.$stage.children().eq(0).remove(), c.pop()) : (c.push(c.length / 2), 
    this.$stage.append(d[c[c.length - 1]].clone().addClass("cloned")), 
    c.push(d.length - 1 - (c.length - 1) / 2), 
    this.$stage.prepend(d[c[c.length - 1]].clone().addClass("cloned")))

**Comment by iandonovan** [comment]
Please upgrade to the newest version of Owl Carousel, released today, and re-open this issue if it persists.
