### ISSUE TITLE
IE 7 Breaks on line 178 of owl.carousel.js

### ISSUE THREAD

**Issue by styke** [smashingboxes/OwlCarousel2#882]
`this._plugins[key[0]+ key.slice(1)]` should be `this._plugins[key.charAt(0).toLowerCase()+ key.slice(1)]`

**Comment by iandonovan** [comment]
[This issue is fixed on both develop and master](https://github.com/smashingboxes/OwlCarousel2/commit/727d1f3c7940089c513ebea962e6d19831b664f8)

You can now get the newest version from bower.
