### ISSUE TITLE
hash nav and loop: true

### ISSUE THREAD

**Issue by Alexufo** [smashingboxes/OwlCarousel2#891]
Hi, thanks for greatest slider!!! It is a unbelievably cool!!!
I use hash navigation with loop: true and navigation is not working well. Loop: true meaning cloning objects with hash tag ids and navigation cant find uniq links for objects i suppose. I think need add this info into Doc in Hash tag section.

**Comment by KennethAshley** [comment]
@Alexufo Thanks for loving the slider! If you have anything you'd like to add please submit a [Pull Request](https://github.com/smashingboxes/OwlCarousel2#pull-requests)!
