### ISSUE TITLE
Issues with image widths and overlapping cards in Chrome.

### ISSUE THREAD

**Issue by PeterBowater** [smashingboxes/OwlCarousel2#895]
As per this issue, I am experiencing this in Chrome mobile: #875 

![screen shot 2015-06-26 at 09 18 42](https://cloud.githubusercontent.com/assets/807991/8373409/5fb36a46-1be4-11e5-8edc-20ea7f75886d.png)

As with other users, using a $(window).load(function(){.........})) has solved the issue.

This is with current (today) code.

**Comment by PeterBowater** [comment]
Actually, that hasn't fixed it on slower connections still, though it seems intermittent, I guess depending on how slow the connection is.

Also, sometimes the slideshow appears OK for a moment, and then pulls back to approx a third the width of the screen, and the markup round the carousel has lots of strange widths associated (0px!), this often seems to be after a scroll event, which on Android devices at least may trigger anything attached to window.height():

<div class="owl-stage" style="transform: translate3d(0px, 0px, 0px); transition: 0s; -webkit-transition: 0s; width: 0px;">
<div class="owl-item active" style="width: 0px; margin-right: 0px;">
<div class="item introbox ">	
#######################				
</div>
</div>
<div class="owl-item" style="width: 0px; margin-right: 0px;">
<div class="item introbox ">					
#######################
</div>
</div>
</div>

**Comment by PeterBowater** [comment]
I have found that this is reproducible when the height of the document changes, this occurs on a mobile when the address bar disappears as you scroll down, so can be very easily broken on mobile.

To reproduce on desktop, just change the height of the browser.

Both tested in Chrome (mobile and desktop)

**Comment by PeterBowater** [comment]
More info..... in onResize() this.$element.width() is getting returned as 0, this is probably the crux of the problem.

Other than that I'm not an expert, but be great if you could look at this!

Thanks!


Peter.

**Comment by greg5green** [comment]
Please provided a reproducible test case as described in https://github.com/smashingboxes/OwlCarousel2/blob/develop/CONTRIBUTING.md#bug-reports and we'll see if we can't figure this out.
