### ISSUE TITLE
A different animateOut classname for owl-next and owl-prev

### ISSUE THREAD

**Issue by gabfire** [smashingboxes/OwlCarousel2#911]
Thank you very much for the awesome script.
CSS3 animations are great. It would have been just perfect if we could use a different CSS3 effects for both owl-next and owl-prev functions.

That way when using fadeOutLeft for owl-next, we could use fadeOutRight for owl-prev and have slide items to slide out correct direction of the screen.

**Comment by greg5green** [comment]
I'm going to close this as being a duplicate of #958.
