### ISSUE TITLE
Transitions only working in Firefox

### ISSUE THREAD

**Issue by angelofm** [smashingboxes/OwlCarousel2#912]
Transitions don't work in Chrome 43 or IE 11, only work in Firefox.

**Comment by angelofm** [comment]
Link to the page I tested this: http://owlgraphic.com/owlcarousel/demos/transitions.html

**Comment by greg5green** [comment]
That example is from the original OwlCarousel project. Their issue tracker can be found [here](https://github.com/OwlFonk/OwlCarousel/issues).

If you have a similar issue with OwlCarousel2, please follow up and we'll re-open the issue here.
