### ISSUE TITLE
Right to Left Support

### ISSUE THREAD

**Issue by HamidRezaSepehr** [smashingboxes/OwlCarousel2#921]
It would be great if we could use Owl carousel for Right to Left websites, right now I added dir="rtl" to the html tag and Owl stopped working!
Thanks guys

**Comment by Flatroy** [comment]
You just need add rtl:true and Owl will change direction from Right to left.
http://www.owlcarousel.owlgraphic.com/demos/rtl.html

**Comment by HamidRezaSepehr** [comment]
Cool, I'll check it out. Thanks buddy.
