### ISSUE TITLE
Getting the real index of item while have loop enabled.

### ISSUE THREAD

**Issue by NPanayotov** [smashingboxes/OwlCarousel2#923]
The issue that i'm having is when i try to create a custom thumbnails navigation for the owl carousel. 

So basically my markup is:

```html
<div class="slider-nav">
	<ul>
		<li>
			<a href="#">
				<img src="css/images/temp/" alt="">
			</a>
		</li>
		
		<li>
			<a href="#">
				<img src="css/images/temp/" alt="">
			</a>
		</li>
		
		<li>
			<a href="#">
				<img src="css/images/temp/" alt="">
			</a>
		</li>
	</ul>
</div><!-- /.slider-nav -->
```

and this is my js:
```javascript
            $('.slider-nav').on('click', 'a', function (event) {
				var $this = $(this);
				var $parent = $this.parent();
				var idx = $parent.index();

				$carousel = $this.parents('.slider').find('.slides');

				$carousel.trigger('to.owl.carousel', idx, 500);

				$parent.addClass('current')
					.siblings().removeClass('current');
			
				event.preventDefault();
			});
```

This code works if i don't have loop enabled. When i have loop enabled the carousel clones the slides and my index isn't the correct one.

My question is how can i target the correct index when having cloned slides?
Does anyone got a solution for this?

**Comment by thirdender** [comment]
What did you end up doing?

**Comment by NPanayotov** [comment]
I used "dotsContainer" but the trick there use markup that the slider likes you can see the plnkr demo

http://embed.plnkr.co/FSDm1BhcWmINU2qlQsuo/preview

**Comment by opfertunes** [comment]
This is giving me the correct absolute index of the active image, with loop:true
```
owl.on('changed.owl.carousel', function(event) 
{
 
   var pos = event.relatedTarget.normalize(event.item.index, true) -2; 
   if (pos < 0)
   {
        var sourceImages = getYourImageListHere(); //your source array of images/image data.... 
        var imgCount = sourceImages.length;
        pos = imgCount + pos;
    }
    console.debug("index in original image list is ", pos);              
});
```

**Comment by shakirmsr** [comment]
How can we get the active slide index on click, while having the loop enabled

**Comment by aigre87** [comment]
$('.owl-carousel-1').on('click', '.owl-item', function(e) {
  var carousel = $('.owl-carousel-2').data('owl.carousel');
  e.preventDefault();
  carousel.to(carousel.relative($(this).index()));
});

**Comment by SergeyMell** [comment]
This worked for me:
```
owl.on('changed.owl.carousel', function (e) {
            if (e.item) {
                var index = e.item.index - 1;
                var count = e.item.count;
                if (index > count) {
                    index -= count;
                }
                if (index <= 0) {
                    index += count;
                }
                return index;
            }
        });
```

**Comment by cs09g** [comment]
@opfertunes
`var pos = event.relatedTarget.normalize(event.item.index, true) -2;`
should be
`var pos = event.relatedTarget.normalize(event.item.index, true) - Math.ceil(event.item.count / 2);`

**Comment by jsPasha** [comment]
```
onChange: function(e) {
   var index = (e.property.value - Math.ceil(e.item.count / 2)) % e.item.count || 0;
   console.log(index)
}
```

**Comment by dualjack** [comment]
Small change to @jsPasha code:

```js
onChange: function( e ){
    var index = ( 1 + ( e.property.value - Math.ceil( e.item.count / 2 ) ) % e.item.count || 0 ) || 1;
    console.log(index);
}
```

In some cases it started with -1 if URLhashListener option was set to true.

**Comment by ozgurg** [comment]
Remove "dots" property in the options. Then access the real index by "event.page.index". When you remove "dots" property, "event.page.index" will be start 0 instead -1.

But if you are using dots feature, I don't know the right answer.

Example:
```javascript
owl.owlCarousel({
  loop: true,
  margin: 0,
  nav: false,
  dots: false, // Remove this
  items: 1,
  mouseDrag: true,
  touchDrag: true,
  autoplay: true,
  autoplayHoverPause: false,
  smartSpeed: 1000,
  autoplayTimeout: 4000
});
```

(Tested on v2.3.4)

**Comment by marcelo2605** [comment]
I found a small issue in @dualjack solution: when I'm in the first slide and go back to the last (`loop: true`), the index not change.

**Comment by mmdm95** [comment]
Hi, I see this solution from [this url](https://codepen.io/codeninja93/pen/AXadWQ) and change it a little bit. Finally this is the result. Test it to see if its OK or NOT...

```
var items = event.item.count;     // Number of items
var item  = event.item.index - 1; // Position of the current item

// it loop is true then reset counter from 1
if(item > items) {
   item = item - items
} else if (item < 1) {
   item = items;
}
```

**Comment by relaxdd** [comment]
Unfortunately, none of the above options work, my example was different, but unfortunately it also sometimes crashes and returns -1 index

`const elem = $(target).find(".owl-item").eq(index);
return $(target).find(".owl-item:not(.cloned)").index(elem);`

**Comment by Abinash-Developer** [comment]
jhgjghjghjhjghj
