### ISSUE TITLE
Error when loop option used on slideshow with single item

### ISSUE THREAD

**Issue by Dhirajpatel** [smashingboxes/OwlCarousel2#928]
When i used single item with loop option once complete slider then start again white space comes.

i think when we used loop and autoplay function combine then generate issue.

used code - $('.owl-carousel').owlCarousel({
                items: 1,
                loop: true,
                margin: 10,
                autoplay:true
              });

**Comment by jameskerr** [comment]
Yes, I am experiencing this same issue.  It looks as though the "loaded" event is not getting fired.  My config looks like so:  

```js
  $('main').owlCarousel({
    items: 1,
    loop: true
  });
```
And the html is looking like this.
```html
<main class="owl-carousel owl-theme owl-loading" role="main">
```

When I remove the option `loop: true`, everything works perfectly.   

I'd be happy to look into the issue myself and submit a pull request.  Perhaps you can point me in the right direction?

**Comment by JoshAinsworth** [comment]
I just fixed a similar sounding issue by giving the '.owl-item' elements a z-index of 1 - give it a try?

**Comment by Dhirajpatel** [comment]
Thanks Josh, it works.

**Comment by manelio** [comment]
Good point, Josh :+1:

**Comment by greg5green** [comment]
This is fixed in beta 3 ([test case](http://codepen.io/anon/pen/YXoqBQ))

**Comment by rajeeshkp** [comment]
But its not working when items:2
