### ISSUE TITLE
content manipulation

### ISSUE THREAD

**Issue by Alex-Nabu** [smashingboxes/OwlCarousel2#933]
There was a reinit method in v1. I notice it seems to have been removed in v2. Whats the suggested method for updating the content(not adding) of the carousel now

**Comment by greg5green** [comment]
For changing out content, you would want to use the `replace.owl.carousel` option.

Right now, you need to call `refresh.owl.carousel`, as well as replace -- this might change in the future.

Example:
```
var html = [
    '<div class="item">',
        '<h4>14</h4>',
    '</div>',
    '<div class="item">',
        '<h4>15</h4>',
    '</div>',
    '<div class="item">',
        '<h4>16</h4>',
    '</div>'
].join('');

$('.owl-carousel')
    .trigger('replace.owl.carousel', html)
    .trigger('refresh.owl.carousel');
```

There is not currently a way to reset the options of the carousel without doing `destroy.owl.carousel`. This would be something nice to add to going forward, so I have opened #935 for that.
