### ISSUE TITLE
How to display two rows of slides at a time?

### ISSUE THREAD

**Issue by luo33220** [smashingboxes/OwlCarousel2#939]
And can you mix it with pictures and video?
Like the following diagram：
![0716160054](https://cloud.githubusercontent.com/assets/6268983/8718116/038db6fe-2bd4-11e5-994e-9c86591e8a70.jpg)

**Comment by hoppithek** [comment]
simply put two elements into each slide (above each other), in your example they are all the same width, when above each other. Make sure to force them to the same height also, otherwise it wont look good.

You could mix anything like this, but the video plugin relies on fixed dimensions.

**Comment by luo33220** [comment]
after, I thought of the way is put eight elements into each slide ,and Make sure to force them to the same height and width then "float:left".Your idea is better than mine.thank you
