### ISSUE TITLE
Use <button> elements for buttons

### ISSUE THREAD

**Issue by SamPotts** [smashingboxes/OwlCarousel2#942]
Using `<span>` and `<div>` for buttons isn't ideal. Could it use the correct element? In this case `<button>` or if not, even a `<a href="#id-of-item">` would be better as at least they can get focus and have the correct semantics for screen readers etc. 

I'm happy to take a look if you'd like... 

Cheers

**Comment by gearsdigital** [comment]
You are able to [configure navigation elements](https://github.com/smashingboxes/OwlCarousel2/blob/develop/src/js/owl.navigation.js#L127).

```js
    $('.my-carousel').owlCarousel({
        navElement: 'button'
    });
```

**Comment by SamPotts** [comment]
Awesome thanks.

**Comment by SamPotts** [comment]
Doesn't seem to work for the dots though which is a shame.

**Comment by MichielBijl** [comment]
Would be nice if this was [in the documentation](http://smashingboxes.github.io/OwlCarousel2/docs/api-options.html).
