### ISSUE TITLE
Responsive option issue on iPhone

### ISSUE THREAD

**Issue by sodbileg** [smashingboxes/OwlCarousel2#943]
My responsive option is below.
```javascript
responsive: {
    0: {
        items: 1
    },
    992: {
        items: 3
    }
}
```
Sometimes, it appears as 3 columns, but after I refresh my browser, it appears as 1 column on iPhone 6 and 6 Plus.

![screenshot 2015-07-20 11 34 52](https://cloud.githubusercontent.com/assets/1418797/8769244/5231d7fa-2ecb-11e5-98d3-c0510a862113.png)

**Comment by greg5green** [comment]
Can you provide a test case for debugging? Something reproducible on codepen, jsfiddle, or jsbin? Thanks.

**Comment by valerios** [comment]
I am having the same problem.
Featured Proejcts section on this page:
http://icreatedev.com.au/darren/
