### ISSUE TITLE
Idea: Autoplay Rewind

### ISSUE THREAD

**Issue by hkan** [smashingboxes/OwlCarousel2#944]
Thanks for the amazing plugin. I have used it countless times on many of both mine and customers' websites.

As OwlCarousel's options, we have both the `loop` and the `autoplay`. The issue I'm having is I don't want my carousel to *loop* but I want the autoplay to rewind when it is at the last item. So I'm suggesting a `autoplayRewind` option which works as explained below.

**Default behavior:** Regardless of `loop` option, if carousel is *autoplay*ing, and it's currently at the last item, it should rewind back to the first item.

**Optional:** If `loop` is *true*, rewinding acts like autoplay is moving to the next item, but if `loop` is *false*, rewinding actually rewinds back to the first item. (Not sure if I could clearly explain that.)

**Comment by greg5green** [comment]
Thanks for the well written feature request. "Unfortunately," this is already a feature that exists. You an just use the `rewind: true` option instead of `loop: true` and it will rewind. And yes, it works with `autoplay` too.

I made an [example](http://codepen.io/anon/pen/NqZxbr)
