### ISSUE TITLE
Destroy() Method has some problem with resize events...

### ISSUE THREAD

**Issue by StarStep** [smashingboxes/OwlCarousel2#952]
On Chrome event after destroing 
---> $('.slider').trigger('destroy.owl.carousel'); 
i can see this error in console:
---> Uncaught TypeError: Cannot read property '_onResize' of null
Here the webpage: http://socialtab.it/beta/chiusagrande/

Part involved >
c.prototype.onThrottledResize = function() {
g.clearTimeout(this.resizeTimer);
this.resizeTimer = g.setTimeout(this.e._onResize, this.settings.responsiveRefreshRate)
}

Thanks for your help (y)

**Comment by greg5green** [comment]
I do notice this issue on your site, but upon further investigation, you are running an older version of the plugin. It is fixed in beta 3 (I think via 2064682082e5127620b07f5d4d97a8e883e3d440).

Please upgrade to the newest version and if this issue still exists, we can reopen it.

**Comment by harmony7** [comment]
@greg5green The home page still links to beta 2.4, rather than the beta 3 that is on the releases page. If you have the chance, you may want to update that home page link.

And it seems this problem has gone away (at least for me) with beta 3.
