### ISSUE TITLE
Hide/show the prev/next button when showing 1 item at a time

### ISSUE THREAD

**Issue by cheeminjun** [smashingboxes/OwlCarousel2#955]
Seems like active class is placed on at least 3 items at a time. How do I detect when I'm at first/last item when showing 1 item on screen?

**Comment by dashukin** [comment]
Hi @cheeminjun 

You could use some API to set appropriate classes when first or last page is visible:

```javascript
var carousel,
      carouselInstance,
      totalItems,
      itemsPerPage,
      currentIndex,
      isFirstPage,
      isLastPage,
      firstPageAction,
      lastPageAction;
     
carousel = $('#your-carousel-id');
carouselInstance = carousel.data('owlCarousel');

processCarouselEdgePosition ();
carousel .on('changed.owl.carousel', processCarouselEdgePosition);

function processCarouselEdgePosition () {
      totalItems = carouselInstance .items().length;
      currentIndex = carouselInstance.current();
      itemsPerPage = carouselInstance.settings.items;
      isFirstPage = currentIndex  === 0,
      isLastPage = (currentIndex + itemsPerPage) >= totalItems;
      firstPageAction= isFirstPage ? 'addClass' : 'removeClass',
      lastPageAction= isLastPage ? 'addClass' : 'removeClass';

      carousel[firstPageAction]('firstPage');
      carousel[lastPageAction]('lastPage');
}

```

This example doesn't depends on how many items per page you have.
And of course you could run your own logic based on "isFirstPage" and "isLastPage" values.

**Comment by greg5green** [comment]
In beta 3, we already put a disabled class on the prev or next button if it's the first or last slide. I've made an [example](http://codepen.io/anon/pen/RPzrrm) showing an example of hiding prev/next.

If this isn't what you meant, please let me know and we'll re-open.

**Comment by cheeminjun** [comment]
Hi @dashukin, I didn't have the chance to test out your solution, but thanks for posting. 
@greg5green  your example is exactly what I meant :)

**Comment by charmcat** [comment]
This is great. Thanks!
