### ISSUE TITLE
isnumeric beta 2.4. zepto

### ISSUE THREAD

**Issue by janus007** [smashingboxes/OwlCarousel2#957]
Please note that beta 2.4 uses an unsupported zepto function isnumeric which causes owlCarousel to chrash.

the old beta 1.8 which is demonstrated here and says "works" is actually misleading:
http://demo.lanrenzhijia.com/2014/owl0509/demos/zepto.html

**Comment by greg5green** [comment]
This is still an issue in beta-3.

**Comment by janus007** [comment]
That was quick :) :+1:
