### ISSUE TITLE
Owl carousel 2 cloned item click events not firing

### ISSUE THREAD

**Issue by ui-matt** [smashingboxes/OwlCarousel2#962]
I'm currently using Owl Carousel 2.0.0-beta.2.4 in development to keep the carousel centered and loop the items which works nicely.

For some reason the cloned items that Owl generates when setting loop: true doesn't seem to fire on click. You will see in the example I've put together below that every other item alerts the click when fired but if the item has been cloned it doesn't seem to register the click event.

https://jsfiddle.net/5fyhtm51/

**Comment by dashukin** [comment]
Hi, @ui-matt 
1. You could still use event delegation to make all your clicks work fine with some kind of micro-optimization by reducing memory for every click handler that you attach in your example.
```javascript
$('#multiple-carousel').on('click', '.item', function () {
    alert("click");
});
```

2. There is a little time gap in your example, when new items are not cloned yet, but your click handler is already applied to existing items. That's another reason to use event delegation.

**Comment by ui-matt** [comment]
Ah nice!

Seems to work a treat, thanks for that @dashukin

**Comment by negativefix** [comment]
Is there way to get item index for the clicked item? I woud like to determine which item is clicked.

**Comment by TheOddler** [comment]
@negativefix Did you ever find how to properly get the index?

Using `n = $(this).index();` the index is all over the place, I guess because of the cloned items.

**Comment by saurabh-sharma** [comment]
#2021 Should fix this issue.

**Comment by Askhabov-HM** [comment]
> @negativefix Did you ever find how to properly get the index?
> 
> Using `n = $(this).index();` the index is all over the place, I guess because of the cloned items.

add  data-index=" i "
