### ISSUE TITLE
control items (nav/dots) visible when only one page

### ISSUE THREAD

**Issue by AlexandreKilian** [smashingboxes/OwlCarousel2#967]
currently, if you scroll by page and have a nav active, there's no way of hiding it when there happens to be only one page. Having controls that are useless because there are no pages to go to is pointless.

**Comment by greg5green** [comment]
In beta 3, this is "fixed" -- we only display nav and dots if there is somewhere to navigate to. This behavior will hopefully be changing in the future to always show if you pass `nav: true`, but maintain the old functionality with `nav: 'auto'` or some similar syntax (as mentioned in #979)

**Comment by greg5green** [comment]
btw, meant to post this before: [test case I used to make sure it behaved that way](http://codepen.io/anon/pen/OVeypr)
