### ISSUE TITLE
Bigger image in the middle

### ISSUE THREAD

**Issue by StephaneJuban** [smashingboxes/OwlCarousel2#973]
Hi,

I don't see any option to detect the image in the middle of the carousel.
I was wondering and trying to implement something like this :
<img width="325" alt="owlcarousel_featured" src="https://cloud.githubusercontent.com/assets/2980518/9090726/407f3e52-3b9c-11e5-9734-b53e5c9cf081.png">

But to do that I must detect the image in the middle and add some CSS to make it bigger. Is there an option to make the image in the middle with a special class like `class="owl-item active middle"` ?

**Comment by StephaneJuban** [comment]
Never mind, just discovered the option `center` in the source code. According to [the official doc](http://smashingboxes.github.io/OwlCarousel2/docs/api-options.html), I was assuming this option would center the list horizontally.

> Center item. Works well with even an odd number of items.

**Comment by spointecker** [comment]
hey @StephaneJuban 
have you ever implemented the "bigger in center" functionality? I was currently looking for it for owl carousel! :)
