### ISSUE TITLE
Add new items with loop:true

### ISSUE THREAD

**Issue by dbeja** [smashingboxes/OwlCarousel2#989]
Hi,

I was able to add dynamically new items with:
```javascript
_.$slideshow.trigger('add.owl.carousel', [$(html)]).trigger('refresh.owl.carousel'); 
```

But if the carousel has the option loop: true, the new items are added after the cloned items of the loop and the cloned items don't change, so everything gets messed up.

Any workaround for this?

**Comment by greg5green** [comment]
@dbeja This issue is fixed in beta 3, so the workaround is to upgrade :). You can get the newest version from bower or from [the website](http://smashingboxes.github.io/OwlCarousel2/)

Test case I used to verify that this is fixed: http://codepen.io/anon/pen/gpNbwO?editors=101

**Comment by dbeja** [comment]
Great! Tested and it's working!
I've also noticed that it's not needed anymore to add the div.owl-item for each item added.

Thanks!
