### ISSUE TITLE
Destroy is not complete

### ISSUE THREAD

**Issue by kjfranke** [smashingboxes/OwlCarousel2#990]
Destroy needs an extra unwrap on line 1557
On resize it generates errors on 623 to fix it i put this line in an if statement: if(this.e){

Added an .removeClass('owl-loaded') on line 1554

**Comment by greg5green** [comment]
This is a dupe of #404, #485, and #952 and is fixed in beta 3.

**Comment by arodger3** [comment]
It doesnt work in beta 4
