### ISSUE TITLE
Autocalculate arrow position

### ISSUE THREAD

**Issue by SalahAdDin** [smashingboxes/OwlCarousel2#994]
I see that the all slider plugins use the prev and next arrow by default, i like it.
I don't mean that is bas put text in side of arrow, i put the arrows but, we have to put the arrow position in the css.
I have to put two sliders in a same page, this means that i have put to different css rules, but, with the other sliders, i haven't do this because the plugin do this for me.

See:
![problema flechas](https://cloud.githubusercontent.com/assets/5034215/9375114/79853130-46c2-11e5-8d11-dc868b715037.png)
Here is good, but, the next isn't good:
![feature autocalculate arrows](https://cloud.githubusercontent.com/assets/5034215/9375120/82f3fc24-46c2-11e5-83e6-377b7a1d4531.png)

I think that will be that in the case of we put the arrows with navText, the plugin calculate the arrow's position for more dinamyc work :D

**Comment by greg5green** [comment]
This is a pretty opinionated decision to make (and one I don't think we're prepared to make, at least at the moment).

There is a way to deal with your problem though. We support `navContainerClass` and `navClass` properties that allow you to set custom classes on the prev/next elements (and their parent). You set these when invoking the carousel, so if you have two different carousels, you just invoke them with different options if you need to style the navigation buttons differently. For an example of this, check this [Codepen](http://codepen.io/anon/pen/xGoOLr) out.

Also, in your example images, it looks like you're just trying to vertically center the buttons in your carousel (and doing it with hard pixel/em/rem values). There are a couple ways to center stuff like that in modern browsers that are just the browser doing calculations on its own. One example of this is in the Codepen I posted above.

Hope this helps and thanks for your interest in the plugin.

**Comment by SalahAdDin** [comment]
Thank you very much man, i didn't know the translation method, thanks.

**Comment by greg5green** [comment]
Only thing to keep in mind is [browser support](http://caniuse.com/#feat=transforms2d). It's supported in all the browsers for the last few years, but if you have to work with IE8, you'll need a different approach.
