### ISSUE TITLE
How do I disable an item inside the carousel wrapper div?

### ISSUE THREAD

**Issue by barry205** [smashingboxes/OwlCarousel2#996]
Hi all

Everything inside the owl-carousel wrapper turns into an item, works good, but how can I disable an element (in this instance, the <span>) so the carousel ignores it and doesn't create a new slide?

Example:
```html
<div id="home" class="owl-carousel">
<span>Back..</span>
      <div class="slide active">
        <h2>Slide 1</h2>
      </div>
      <div class="slide">
        <h2>Slide 2</h2>
      </div>
      <div class="slide">
        <h2>Slide 3</h2>
      </div>
</div>
```
The above creates 4 slides, I only want 3 and need the span to be ignored. Is this possible without pulling it from the container?

Thanks, Barry

**Comment by greg5green** [comment]
You an do this if you wrap your slides in another div and use the `nestedItemSelector` property.
**NOTE:** `nestedItemSelector` would be the selector of the slides, not the container.

Example HTML:
```
<div id="home" class="owl-carousel">
  <span>Back..</span>
  <div class="slide-container">
    <div class="slide active">
      <h2>Slide 1</h2>
    </div>
    <div class="slide">
      <h2>Slide 2</h2>
    </div>
    <div class="slide">
      <h2>Slide 3</h2>
    </div>
  </div>
</div>
```

Example JS:
```
  $('.owl-carousel').owlCarousel({ nestedItemSelector: 'slide' });
```

**Comment by barry205** [comment]
Thank you! Been trying to figure this out for over a week now, much appreciated Greg :)
