### ISSUE TITLE
How to stop autoplay after users drag??

### ISSUE THREAD

**Issue by StarStep** [smashingboxes/OwlCarousel2#998]
Hi,
is possible to stop the slider after users volountary drag? 
Also the speed is not changing at all if specified in "autoplay.resume" call..
HERE AN ATTEMP: http://jsfiddle.net/nxcgLvLp/7/
Thanks a lot :)

**Comment by greg5green** [comment]
These issues were all fixed in beta 3. [Test case](http://jsfiddle.net/3Lapvjwt/)
