### ISSUE TITLE
AutoWidth with responsive layout doesn't show last image.

### ISSUE THREAD

**Issue by stratboy** [smashingboxes/OwlCarousel2#999]
Hi, I'm using a responsive layout, in this case meaning that simply the container's width will be == window width, or in other words, 100%.

My code:
```javascript
carousel.owlCarousel({
  video:true
  ,URLhashListener:true
  ,startPosition: 'URLHash'
  ,onInitialized: function(){ reset_video_size(); }
  ,onResized: function(){ reset_video_size(); }

  ,responsive:{
    0:{
      items:1
    },
    520:{
      items:2
    },
    1024:{
      autoWidth:true
    }
  }
});
```

Obviously, if I place a 'next' arrow, OR simply drag from right to left, I want to see the next image on the right. Somewhat like the rtl option, but since we start with the first image, that option is not useful here. Please see attachment. The last image (the one with 'XL' wood wall) isn't fully visible, and I won't be able to drag it to the end.

The problem here is that `next.owl.carousel` uses the image on the left to determine the 'next' image, while obviously what we're looking for is the one not visible, thus the image on the far right. Being this a very common carousel situation, I think it can be considered a bug.
The rtl option itself is not useful since the first screen in normal situations should show the first image on the right.

![schermata 2015-08-21 alle 11 51 11](https://cloud.githubusercontent.com/assets/437598/9405897/0ee9558c-47fc-11e5-82f4-4086bd100f0e.png)

**Comment by greg5green** [comment]
Can you please create a test case for this as described in https://github.com/smashingboxes/OwlCarousel2/blob/develop/CONTRIBUTING.md#bug-reports? Thanks.
